tailscale/tailscale-android

android/src/main/java/com/tailscale/ipn/IPNService.java
cmd/tailscale/main.go

Fixes tailscale/tailscale#2102
Updates tailscale/tailscale#1809

Fix routing loop prevention, MagicDNS forwarding over Tailscale.

---

cmd/tailscale/main.go

Fixes https://github.com/tailscale/tailscale/issues/2971

cmd/tailscale: report ChromeOS.

---

cmd/tailscale/backend.go
cmd/tailscale/main.go
cmd/tailscale/ui.go

and normalized the caps style on the first menu item which was inconsistent. Now:

cmd/tailscale: add "Bug report" item to menu

---

cmd/tailscale/backend.go
cmd/tailscale/main.go
cmd/tailscale/ui.go
go.mod
go.sum

And bump tailscale dep, to bring in new ipn.Prefs API and wire up
ExitDNS for Android.
This change has no visible behavior change to anybody unless they
search for "debug" and then hit the "..." menu.
Updates tailscale/tailscale#1738

Add secret Run Exit Node option when "debug" is searched for.

---

cmd/tailscale/main.go
cmd/tailscale/ui.go

Updates tailscale/tailscale#2155

Add "Allow LAN access" checkbox in Exit Node menu

---

README.md

I always forget these and need to go search old bugs for them.

README.md: add some Fire Stick dev docs

---

cmd/tailscale/backend.go

The netstack code on Android was never told about the LocalBackend,
so the peerapi interception wasn't working.
Fixes tailscale/tailscale#4449
Fixes tailscale/tailscale#4293

cmd/tailscale: fix netstack init, call SetLocalBackend

---

android/src/main/java/com/tailscale/ipn/IPNService.java

Fixes https://github.com/tailscale/tailscale/issues/2554

Add GoPro to the apps allowed to skip the VPN.

---

.github/workflows/build.yml

Building tailscale-debug.apk also runs unit tests.

Add continuous integration builder

---

.github/licenses.tmpl
.github/workflows/go-licenses.yml

.github/workflows: add go-licenses GitHub Action

---

android/build.gradle
go.mod
go.sum

go.mod: update for 1.31 dev builds.

---

cmd/tailscale/backend.go
cmd/tailscale/main.go

Updates tailscale/tailscale#2180
Signed-off-by: Andrew Dunham <andrew@du.nham.ca>

cmd/tailscale: show an error when we hit the multiple users Android bug

---

cmd/tailscale/backend.go

cmd/tailscale: set logcfg.FlushDelay

---

android/src/main/java/com/tailscale/ipn/IPNService.java

Fixes https://github.com/tailscale/tailscale/issues/2548

IPNService: add Sonos S1 to the apps allowed to bypass the VPN.

---

Dockerfile

Updates go from 1.17.5 to 1.19.5 in the dockerfile

Dockerfile: go 1.19.5

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/tailscale/ipn/IPNReceiver.java
cmd/tailscale/callbacks.go

Added a new class IPNReceiver to listen to intents silently and connect and disconnect the VPN
Updates: https://github.com/tailscale/tailscale/issues/3547

IPNReceiver: Add intents to connect and disconnect VPN

---

cmd/tailscale/main.go
cmd/tailscale/ui.go

Fixes https://github.com/tailscale/tailscale/issues/2155
This is my first time working with Go on Android, so bear with me. 
Review is much appreciated.
Screenshot:

Add DNS/routing prefs like on desktop

---

cmd/tailscale/backend.go

More generally, make the `logtail.Config` similar to the one used by clients for other platforms.
Updates tailscale/corp#9230

cmd/tailscale: upload client metrics

---

cmd/tailscale/backend.go

The c2n endpoint was not working since we did not configure the flush function (same issue that was previously fixed in the iOS client in tailscale/corp#9939).
Updates tailscale/corp#8564

cmd/tailscale: enabled logtail flushing for the Android client

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/java/com/tailscale/ipn/App.java
android/src/main/java/com/tailscale/ipn/IPNReceiver.java
android/src/main/java/com/tailscale/ipn/IPNService.java
android/src/main/java/com/tailscale/ipn/StartVPNWorker.java
android/src/main/java/com/tailscale/ipn/StopVPNWorker.java
cmd/tailscale/callbacks.go

~~This is still a WIP, still testing, but created this draft so I can start to get the PR ready~~
Ready for review now.

Add intents

---

cmd/tailscale/backend.go

Sometimes we try a dozen different ways to read the phone's DNS
settings and it still comes back empty. In that case, if we're already
on a Google-ified Android phone, just use Google's Public DNS servers
as the ultimate fallback, as we already do on ChromeOS to work around
ChromeOS Android VpnBuilder bugs.
Updates tailscale/tailscale#8006 etc etc

cmd/tailscale: use Google as DNS of last resort

---

cmd/tailscale/main.go
cmd/tailscale/ui.go

Reverts tailscale/tailscale-android#86
This change has been reverted in the last two releases. Reverting in main until fixes have been made.

Revert "Add DNS/routing prefs like on desktop"

---

.gitignore
android/build.gradle
android/src/main/AndroidManifest.xml

Essentially periodic maintenance.

android: update Android Gradle Plugin as recommended by Android Studio

---

cmd/tailscale/backend.go
go.mod
go.sum

go.mod: bump oss

---

cmd/tailscale/main.go

Fixes tailscale/corp#14056
Updates tailscale/tailscale#8967

cmd/tailscale: prefer showing Sharer user over Owner user

---

cmd/tailscale/backend.go

This is a quick fix, we should come back and try to reorganize this later.
Updates tailscale/tailscale#9374

cmd/tailscale: avoid creating multiple netmon instances

---

cmd/tailscale/backend.go

Fixes https://github.com/tailscale/corp/issues/15388

cmd/tailscale: add tun Wrapper and call Start()

---

android/gradle.properties

This fixes the issue where building in Android Studio OOMs
Fixes #10714

build.gradle: increase JVM memory settings

---

.gitignore

.gitignore: ignore Java profiling files

---

.gitignore

.gitignore: ignore IDE

---

android/src/main/java/com/tailscale/ipn/DnsConfig.java

DnsConfig: get rid of unnecessary isEmpty check

---

cmd/tailscale/backend.go

Causes a JNI crash because 1b42117791266251b41959fc18e6c6215a85f739 removed those methods when fixing our connectivity monitoring.
Updates tailscale/tailscale#10107

cmd/tailscale: remove obsolete DNS config logging

---

Dockerfile

Dockerfile: update to use go 1.22

---

cmd/tailscale/main.go

cmd/tailscale/main: clean up unused event

---

Makefile

Makefile: update go version for bumposs

---

cmd/tailscale/main.go

cmd/tailscale/main: remove debugging comment

---

android/src/main/java/com/tailscale/ipn/ui/localapi/LocalAPIRequest.kt
android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt

android: code review suggestions

---

.gitignore

Updates tailscale/tailscale#10748
The built aar should not be checked into android_legacy.

cmd/tailscale/main: remove tracked aar lib

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ui/localapi/LocalAPIClient.kt
android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
android/src/main/java/com/tailscale/ipn/ui/service/IpnManager.kt
android/src/main/java/com/tailscale/ipn/ui/service/IpnModel.kt
cmd/localapiservice/localapishim.go

Review feedback and stylistic improvements from @oxtoacart

android: code review feedback and stylistic improvements

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ui/localapi/LocalAPIClient.kt
android/src/main/java/com/tailscale/ipn/ui/localapi/LocalAPIRequest.kt
android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
android/src/main/java/com/tailscale/ipn/ui/model/IpnState.kt
android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
android/src/main/java/com/tailscale/ipn/ui/service/IpnManager.kt
android/src/main/java/com/tailscale/ipn/ui/service/IpnModel.kt
android/src/main/java/com/tailscale/ipn/ui/service/PrefsEditor.kt
android/src/main/java/com/tailscale/ipn/ui/util/Flag.kt
android/src/main/java/com/tailscale/ipn/ui/util/LoadingIndicator.kt
android/src/main/java/com/tailscale/ipn/ui/util/StateFlow.kt
android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/BugReportViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
android/src/main/res/values/strings.xml
cmd/localapiservice/localapishim.go

android: implement exit node picker

---

android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt

android: make ExitNodePickerViewModel reactive

---

Makefile

- Provide version flags to the build
- Add the new build targets to all
- Move the old fdroid and release builds close to their siblings
- Build gomobile into android/build/go for a small reduction in linker wait time
- Fix the test target so it's now triggering the gomobile build
- Make the install target use the new android build
- Add missing items to the clean target

Makefile: cleanup the new builds more

---

android/src/main/java/com/tailscale/ipn/IPNService.kt

Kotlin requires a nullable optional here.  The rest of this is ktfmt

android: make intent optional in onStartCommand

---

Makefile

Add `make help` command, which prints available commands and their description.  I'm not 100% sure which commands should be documented, so took an initial attempt at it.
This also makes `make help` the default command, aligning it with the Makefiles in corp and oss.

Makefile: add help text to make commands

---

android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/DnsConfig.java

Closes #ENG-3005
I manually tested that this works on both Wifi and Cell, and that I'm able to switch Wifi off and on and maintain network connectivity.

android: correctly grab DNS settings

---

android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
android/src/main/java/com/tailscale/ipn/ui/util/InputStreamAdapter.kt
android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt
go.mod
go.sum
libtailscale/interfaces.go
libtailscale/localapi.go

Supports multipart requests to localapi

android: add CallLocalAPIMultipart

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/TailscaleLogoView.kt

Fixes ENG-2860
Adds a game of life animation with the Tailscale logo when launching the app and waiting for the VPN tunnel to be established.

android/ui: add game of life to show progress when connecting (ENG-2860)

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ui/util/ClickableOrGrayedOut.kt
android/src/main/java/com/tailscale/ipn/ui/util/Lists.kt
android/src/main/java/com/tailscale/ipn/ui/util/LoadingIndicator.kt
android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePickerList.kt
android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
android/src/main/res/values/strings.xml

android: style exit node picker per Material UI and add disable button

---

android/src/main/AndroidManifest.xml
android/src/main/res/values/string-arrays.xml
android/src/main/res/values/strings.xml
android/src/main/res/xml/app_restrictions.xml

Fixes ENG-2926
Adds an `app_restrictions.xml` file with our available MDM policies, and a new entry to the AndroidManifest.xml file to declare its availability.

android: add app_restrictions.xml and manifest entry

---

android/src/main/java/com/tailscale/ipn/App.kt

-Once we edit prefs with wantRunning, also update QuickToggleService 
-Start Notifier in App so that we are observing tile status
Closes #ENG-2869

App.kt: fix Quick Tiles

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ui/view/IntroView.kt
android/src/main/res/values/strings.xml

fixes ENG-2910
adds a one-time intro screen mostly identical to the one presented in the legacy app.

android/ui: add one-time intro screen

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/res/values/strings.xml

Fix logged out strings
Fixes ENG-3048

MainView, strings: show toggle when logged out

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt

android/ui: navigate back home after switching users

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt

android/ui: display correct flag on exit node picker

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt

android/ui: disable navigation animations

---

android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt

UserSwitcherView: hide logout option if not logged in

---

android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
android/src/main/res/values/strings.xml

android/ui: apply exit node selector design feedback

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt

view model should also check if the node is self and if connected when determining connection status string and conncolor

ui: fix PeerDetails connection status and conncolor

---

android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt

android/ui: distinguish Tailnet domains in user view

---

android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/util/ClipboardValueView.kt
android/src/main/java/com/tailscale/ipn/ui/util/Lists.kt
android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
android/src/main/java/com/tailscale/ipn/ui/view/FeatureStateView.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
android/src/main/java/com/tailscale/ipn/ui/view/PermissionsView.kt
android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt
android/src/main/res/values/strings.xml

From yesterday's walkthrough with @kari-ts and @sonovawolf

android/ui: more styling tweaks

---

android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/util/AutoResizingText.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt

android/ui: auto-resize tailnet name to fit space

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt

Use CustomTabsIntent to launch login, but fall back to regular intent if Chrome is not installed When logging in, on change in state to login complete, bring activity back to focus
Fixes ENG-2928

MainActivity: bring activity to focus on login

---

android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
android/src/main/java/com/tailscale/ipn/ui/model/Types.kt
android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
android/src/main/java/com/tailscale/ipn/ui/util/TimeUtil.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/PeerView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
android/src/main/res/values/strings.xml

fixes ENG-2912
copies and adds the a key expiry banner identical to the one on iOS.
fixes a couple of small layout issues with the search bar

android/ui: add key expiry banner

---

android/src/main/java/com/tailscale/ipn/ui/model/Permissions.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/PermissionsView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
android/src/main/res/values/strings.xml

Also, programmatically check to see if notifications are enabled on older Android versions.

android/ui: show only missing permissions in settings

---

android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
android/src/main/res/drawable/androidicon.xml

android/ui: new icon for about screen

---

android/src/main/java/com/tailscale/ipn/IPNService.kt
libtailscale/backend.go
libtailscale/callbacks.go
libtailscale/interfaces.go

This fixes the issue where when the VPN was turned off by system settings, the toggle was showing the user as conencted
Fixes tailscale/corp#18863

IPNService: on close, edit prefs with WantRunning=false

---

android/src/main/java/com/tailscale/ipn/ui/view/IntroView.kt
android/src/main/res/drawable/androidicon_light.xml
android/src/main/res/values/strings.xml

Restyle the intro screen per UX
Result:

android/ui: restyle the intro screen

---

android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt
android/src/main/res/values/strings.xml

android/ui: make it more obvious that account settings row is clickable

---

android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePickerList.kt
android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
android/src/main/java/com/tailscale/ipn/ui/view/PermissionsView.kt
android/src/main/java/com/tailscale/ipn/ui/view/RunExitNodeView.kt
android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt
android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt

1. More careful back navigation to avoid navigating to blank screen
2. After adding an account, navigate back to main view

android/ui: navigation improvements

---

.github/workflows/android.yml
Makefile
android/build.gradle

We're no longer using GoogleSignIn, so there's no need for separate product flavors Updates tailscale/corp#18202

build.gradle, Makefile: remove custom fdroid build

---

android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
libtailscale/interfaces.go
libtailscale/syspolicy_handler.go
libtailscale/tailscale.go

port over https://github.com/tailscale/tailscale-android/pull/199 from cmd/tailscale and legacy_android to libtailscale and android/

ui: port syspolicy handler code to new app

---

android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
android/src/main/java/com/tailscale/ipn/ui/view/IntroView.kt
android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
android/src/main/java/com/tailscale/ipn/ui/view/RunExitNodeView.kt

updates tailscale/corp#19057
Adds scrollability to some of the previously fixed-content views so they render properly with larger font sizes or smaller screens.

android/ui: fix accessibility font size issues

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/res/values/strings.xml

ui: show 'No results' when search returns empty

---

android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt

android/ui: sort self peer first in list of peers

---

android/build.gradle
go.mod
go.sum

go.mod: update for 1.65.0

---

android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt

Applies dark mode improvements from session w/ Ale

ui: dark mode improvements

---

android/src/main/res/values/strings.xml

Fix missing character in date format string

ui: fix missing character in date format string for years in strings.xml

---

android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt

Fixes tailscale/tailscale#11708

ui: use 'tlpub' prefix for Tailnet lock key

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt

Use persistent isOn state across recompositions
Fixes tailscale/corp#19194

MainView: fix toggle animation

---

README.md

s/IPNActivity/MainActivity/ for the new app rewrite.

README.md: update for new app

---

go.mod
go.sum
libtailscale/backend.go

android: enable Taildrive

---

go.mod
go.sum

Updates tailscale/corp#16827
Pulls in https://github.com/tailscale/tailscale/pull/11798

android: pull latest OSS

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt

Address content labeling warnings surfaced by pre-launch report
Updates tailscale/corp#18976

android: add content labels

---

go.mod
go.sum
libtailscale/backend.go
libtailscale/tailscale.go

Updates tailscale/tailscale#11874

go.mod: bump oss, plumb new health.Tracker

---

Makefile
android/src/main/java/com/tailscale/ipn/VPNServiceBuilder.kt
libtailscale/backend.go
libtailscale/callbacks.go
libtailscale/interfaces.go
libtailscale/localapi.go
libtailscale/net.go

-Exclude local routes in VPNServiceBuilder
-Maybe update TUN on new state update where state >= starting -Clean up updateTUN
Updates tailscale/corp#18984

libtailscale, android: fix allow LAN access

---

android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
android/src/main/res/values/strings.xml

android: accessibility fixes

---

Makefile

The Makefile has been through a lot of change in recent iterations and is overdue another cleaning.
- Variables still in use are moved to the variable definition area at the top of the file
- Added three distinct sections separated by comment: android build, go build and utility tasks.
- Relocated tasks into one of those three sections as appropriate
- Removed intermediate phony targets from the APK builds, as they're just making the build harder to trace file wise.
- Shifted from a central PHONY definition to incrementally defined dependencies to ensure every non-file task is correctly marked.
- Switch the final APK moves to use install -C to avoid updating the target files unless actually necessary.
- Add some missing dependencies on some tasks, centralized the gradle dependencies into …

Makefile: clean up the Makefile

---

go.mod
go.sum
libtailscale/net.go
libtailscale/tailscale.go

Update net/interfaces to netmon per https://github.com/tailscale/tailscale/pull/11901

android: bump oss and fix missing net/interfaces

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt

Updates tailscale/tailscale#11731
The MDM logic was infinitely recursing.  The custom control url login handler now does what the other functions do and calls into login with a set of pre-populated prefs.  If MDM specifies a custom login server, we force that, regardless of anything the user specified.
This behaviour matches macOS.

android/ui: fix infinite recursion in  custom login

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt

Fixes ENG-3479
Clear routes when switching profiles and reauthenticating. This fixes an issue where previously set routes/DNS configs caused actions to fail.

IpnViewModel: reset vpn state before login/reauth

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/IPNService.kt
android/src/main/res/values/strings.xml

Prevents BackgroundServiceStartNotAllowedException.

android: make IPNService a foreground service

---

android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/StartVPNWorker.java
android/src/main/res/values/strings.xml

Provide descriptions that will be displayed in the Android system notification settings to describe the purpose of each notification channel to the user.

ui: add descriptions to notification channels

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt

android: fix import

---

android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt

Updates tailscale/tailscale#12148

android: hide Accounts if VPN not prepared

---

android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt

Notifier: init app if uninitialized

---

android/src/main/java/com/tailscale/ipn/App.kt

Updates tailscale/tailscale#10104

App: tap on notification brings up main view

---

android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt

ExitNodePicker: recompose when connection status changes

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

The update available banner had been bothering me.

gradle: update to 8.6

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt

Fixes tailscale/tailscale#12281

IpnViewModel: fix NPE

---

android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
android/src/main/res/values/strings.xml

IpnViewModel: fix NPE (#413)
Fixes tailscale/tailscale#12281

android: add MDM info to exit node picker and banner

---

android/build.gradle

Bumping version to 1.67.85 (android 224)

android: bump version code

---

Makefile

Updates tailscale/corp#19670
This makes the keystore path a paramater so it's not expected to be at the repo root, allowing the builder to leave it where ever it happens to get written.

android/makefile: make keystore path a parameter

---

android/build.gradle

To drop dirty and the old version number.

android: bump version code to 228

---

.gitignore

repo: add .DS_Store to .gitignore

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/src/main/java/com/tailscale/ipn/MainActivity.kt
android/src/main/java/com/tailscale/ipn/ShareActivity.kt

ipn: update dependencies

---

Makefile

Updates tailscale/corp#19670
Build optimization to reuse the existing build image and to
remove the individual containers post build.   Image name
is parameterized.

makefile:  reuse image and remove container for builds

---

android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/ShareActivity.kt
android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/DNSSettingsViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/PingViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/TaildropViewModel.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/TailnetLockSetupViewModel.kt

#cleanup
Removed a host of noisy deprecation and unchecked
cast warnings.

android: clean up build warnings

---

.gitignore
Makefile
android/build.gradle
android/src/main/AndroidManifest.xml
docker/DockerFile.amd64-build

updates tailscale/corp#21644
This will build a second tailscale-tv-release.aab with the leanback flag set.

android/makefile: add tv-specific build variant

---

Makefile

Bumping oss and tagging the release are now combined into a single step.   make bumposs will
now bump to the latest OSS, tag the commit and update the version number in build.gradle in
a single step.  We no longer bump the version code, since this is done during the build step based on
the latest code used in the Playstore.
Pushing the resulting tag remains separate since we only want to tag commits  that are merged to
release and main.

makefile: consolidate bump/tag

---

android/build.gradle
go.mod
go.sum

OSS and Version updated to 1.71.22-t855da4777-g32e48dc78e7

android: bumping OSS

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt

Resolves: https://github.com/tailscale/tailscale/issues/13218
* Typing into the textfield to filter machines properly works now
* `searchTerm.collect {}` was unreachable and caused it not to collect input
| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/20eea88c-0458-409c-b114-17517bb1c9d7" /> | <video src="https://github.com/user-attachments/assets/c74c8f1c-6454-4247-851a-6869719d84c6" /> |

android: Fix search not filtering machines from input

---

android/src/main/res/values/strings.xml

Move MDM auth key strings into the MDM strings blcok

android: move string into correct place

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt

android: make settings button focusable and clickable

---

android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt

android: fix Hostname type in MaskedPrefs, it should be String type

---

android/src/main/java/com/tailscale/ipn/ui/util/ClipboardValueView.kt
android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt

android: fix missing imports

---

android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt

android: fix missing '}' issue

---

Makefile
README.md

- Fix volume mounting (positional argument to `-v`)
- Correct the make target name in README
Updates tailscale/corp#19670

Makefile: fix docker-shell command line

---

tool/go

tool/go: fix typo in comment

---

android/src/main/java/com/tailscale/ipn/NetworkChangeCallback.kt

Instead of just tracking our default network, track all of them and decide upon each change which is the "best" option.
Updates tailscale/tailscale#13173

android: rework NetworkChangeCallback to track all networks

---

android/build.gradle
go.mod
go.sum

OSS and Version updated to 1.75.2-t93f61aa4c-ge195def5e23

android: bumping OSS to 1.75.2

---

Makefile

Makefile: update go.toolchain.rev atomically

---

android/src/main/java/com/tailscale/ipn/ui/view/LoginQRView.kt
android/src/main/java/com/tailscale/ipn/ui/viewModel/LoginQRViewModel.kt
android/src/main/res/values/strings.xml

Updates tailscale/tailscale#13277

android: include hex in LoginQRView

---

libtailscale/backend.go

libtailscale: add metrics to NewUserspaceEngine

---

android/build.gradle
go.mod
go.sum

OSS and Version updated to 1.75.80-t8fdffb8da-g2daeee584df

android: bumping OSS to 1.75.80

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/LoginQRViewModel.kt

Hold off on showing the code until there is a place in the admin console for the user to input the code.
Updates tailscale/tailscale#13277

android: don't show hex code yet

---

android/build.gradle
android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt

Bumps our project dependencies to the latest versions. Verified that the project builds properly.

android: update dependencies

---

android/build.gradle
go.mod
go.sum

OSS and Version updated to 1.77.12-ta8f9c0d6e-g753b8d3fb4b

android: bump OSS

---

Makefile

android: update PR description for bumposs to use "bump"

---

Makefile

Makefile: fix typo in comment

---

android/src/main/java/com/tailscale/ipn/ui/viewModel/LoginQRViewModel.kt

Fixes tailscale/tailscale#13277

android: show hex code for TV log in

---

android/src/main/java/com/tailscale/ipn/ui/notifier/HealthNotifier.kt

Fixes tailscale/corp#24582
Android port of tailscale/corp#24719. We were not clearing dependency warnings when a new warning was added which was listed as a dependency of a pre-existing warning. For instance, if `dns-read-os-config-failed` is added to the warnings before `network-status` is added, we were ignoring the dependency by not removing `dns-read-os-config-failed` upon adding `network-status`. This PR addresses that.

HealthNotifier: fix dependent messages handling

---

android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
android/src/main/java/com/tailscale/ipn/ui/view/TaildropView.kt

Properly attach FocusRequester to the root column of TaildropView so that there is a focusable UI element available to receive the focus
Fixes tailscale/corp#25007

android: fix android TV focus requester crash

---

android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/util/FeatureFlags.kt

Until the WIP feature is ready
Updates tailscale/corp#18973

android: put new search behind flag

---

android/src/main/java/com/tailscale/ipn/App.kt
android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
android/src/main/java/com/tailscale/ipn/util/FeatureFlags.kt

Until the WIP feature is ready
Updates tailscale/corp#18973
Signed-off-by: kari-ts <kari@tailscale.com>
Signed-off-by: kari-ts <135075563+kari-ts@users.noreply.github.com>
(cherry picked from commit e500111fb9ed4b02c309a230759fd613679b703d)

android: put new search behind flag (#587)

---

Makefile

Updates tailscale/tailscale#15015

Makefile: update -compat flag

---

android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt

android: enable search for TV

---

Makefile
docker/DockerFile.amd64-build
docker/DockerFile.amd64-shell

Add zip installation to Dockerfile and bump Docker image version
Updates tailscale/tailscale#15210
Signed-off-by: kari-ts <kari@tailscale.com>

android: intall zip

---

libtailscale/net.go

Updates tailscale/tailscale#15506

android: log when VPN not established

---

android/src/main/java/com/tailscale/ipn/ui/view/CustomLogin.kt

Updates tailscale/tailscale#14864

android: add IME action to trigger custom CustomLogin

---

libtailscale/backend.go

Updates tailscale/tailscale#15160

android: use new System with pre-populated event bus

---

libtailscale/backend.go

Updates tailscale/tailscale#16369

libtailscale: set EventBus in wgengine.Config
