tailscale/tailscale-android

- cmd/tailscale/backend.go
Android updates its DNS config in updateTUN() when in response
to several different channels from the backend.
There is not an Android-specific NewOSConfigurator, we end
up pulling in the Linux NewOSConfigurator:
https://github.com/tailscale/tailscale/blob/main/net/dns/manager_linux.go
The Linux DNS manager expects to be able to write to /etc/resolv.conf,
which does not work on Android and causes errors in updating DNS config.
Instead, allocate dns.NewNoopManager to disable the DNS manager, and
rely on the updateTUN() code to handle DNS.
Fixes https://github.com/tailscale/tailscale/issues/1956
> backend: use dns.NewNoopManager.

- cmd/tailscale/backend.go
Using NewNoopManager avoided the errors from trying to overwrite
/etc/resolv.conf, but still didn't fully work. Route DNS
config through the CallbackRouter.
Fixes https://github.com/tailscale/tailscale/issues/1956
> backend: Send DNS config through CallbackRouter.

- android/build.gradle
On 6/24 I built a v43 and started to release it to production,
then decided to do an Internal release first. The Play Store
would not allow v43 to be used again so I built v44, released
it to Internal, and after testing promoted it to Production and
it went into Google's review process.
Crucially, I did not push the tags before going to bed.
On 6/25, not knowing any of this because I hadn't pushed the tags,
Elias built v43 and released it. The Play Store had apparently cleaned
up the state from my abandoned v43 by that point.
This commit increments the build number to v44 so we don't re-use it.
I'm not building an actual release, just incrementing the build
number and pointing to the same git commit. I'm hoping F-Droid will
therefore build exactly the same thing as it did for v43.
I …
> android: bump version code

- cmd/tailscale/ui.go
There are several situations where a peer may only have IPv6:
+ it was authorized using an ephemeral node key
https://tailscale.com/kb/1111/ephemeral-nodes/
+ the Tailnet has IPv4 disabled
https://twitter.com/bradfitz/status/1398380415124082690
So:
+ if a peer has an IPv4 address, display that.
+ if a peer does not have an IPv4 address, display IPv6.
+ If a peer does not have either IPv4 or IPv6 then leave
the address blank and pretend nothing happened.
> ui: show IPv6 address if there's no IPv4 address

- Dockerfile
- Makefile
Tailscale maintains a patched Go toolchain, pulling in
fixes early. Download the toolchain and use it to build.
Fixes https://github.com/tailscale/tailscale/issues/2450
in a better way.
> Makefile: download Tailscale's Go toolchain

- cmd/tailscale/backend.go
- go.mod
- go.sum
Allows use of bootstrap DNS and of a built-in ISRG X1 root
certificate.
Fixes https://github.com/tailscale/tailscale/issues/3046
> backend: use logpolicy.NewLogtailTransport

- android/src/main/java/com/tailscale/ipn/App.java
- cmd/tailscale/main.go
1. Follow
https://developer.android.com/training/monitoring-device-state/connectivity-status-type
to determine whether to report ourself as having connectivity or not.
Tested by turning the Wifi & LTE off and on, seems to work well in
the contrived test case.
2. Call superclass for onLost() and onLinkPropertiesChanged() handlers.
Current Android versions have no code in the superclass of these two
callbacks, but future proofiness.
3. Log when the UI report of LostInternet changes, so we can find it.
Fixes https://github.com/tailscale/tailscale/issues/3542
> ui: more robust isConnected check.

- Makefile
This is intended as a quick fix of the immediate problem:
don't compute the checksum using absolute paths (i.e.
/home/dgentry), use relative paths.
In the future we may rationalize the versioning of the
toolchain to tie the Android toolchain to the one used
for building Linux/macOS/Windows/etc.
Fixes https://github.com/tailscale/tailscale/issues/3596
> Makefile: make toolchain sum not use absolute path.

- Dockerfile
- Makefile
- go.mod
- go.sum
And don't sha1-sum the Go toolchain cache.
Just see if its go binary works.
Updates tailscale/corp#3385
Updates tailscale/tailscale#3596
> go.mod: use Go toolchain rev from oss

- Makefile
- go.mod
- go.sum
It only worked on linux/amd64 before, but we support
{linux,darwin}/{amd64,arm64} for development elsewhere.
Fixes tailscale/tailscale#3669
> Makefile: make toolchain bootstrap work on darwin and arm64

- Makefile
Nowadays basically nobody should set GOROOT. I still do for various
reasons, but that broke this build which then ran our custom toolchain
with a mismatched GOROOT. Clear GOROOT so the default GOROOT is used
(which is the path that matches the Go toolchain in use)
Also, add a "rundebug" target to control adb (phone or emulator)
> Makefile: clear GOROOT, add rundebug target

- android/src/main/java/com/tailscale/ipn/App.java
- android/src/main/java/com/tailscale/ipn/DnsConfig.java
We use strings to pass structured data from the JVM to Go.
In a locale using Indian-Arabic numerals: ۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹
the Java code will format decimal strings using Indian-Arabic
glyphs.
Go doesn't get a locale set automatically by the Android
runtime, so it always parses strings in a default en-US
`unable to parse "lo ١ ٦٥٥٣٦ true false true false false |": expected integer`
Make the Java code format using the ROOT locale. These strings
are purely internal to pass between the two runtimes, they are
not shown to the user.
Fixes https://github.com/tailscale/tailscale/issues/4156
> java: format strings containing integers in ROOT locale.

- cmd/tailscale/ui.go
Android running as an exit node has been implemented behind a magic "debug" search string for three releases. I think we've gotten as much early usage as we're going to get. Move it into the main menu as a regular feature.
> Move run exit node to main menu

- android/src/main/java/com/tailscale/ipn/IPNService.java
Google Stadia, Messages (RCS/Jibe), and Android Auto
don't benefit from being on the VPN, and don't work.
Either they need access to local hardware (Auto, Stadia)
or they're accessing an entirely different communications
channel (Messages). Don't send them through the VPN.
Fixes https://github.com/tailscale/tailscale/issues/2322
Fixes https://github.com/tailscale/tailscale/issues/3460
Fixes https://github.com/tailscale/tailscale/issues/3828
> Add inherently local apps to disallowed list.

- Makefile
- android/build.gradle
- android/src/main/java/com/tailscale/ipn/DnsConfig.java
- android/src/test/java/com/tailscale/ipn/DnsConfigTest.java
Two commits:
--------
intToInetString(0x0101a8c0) returns "-64.-88.1.1" because Java
integers are always signed. There is not a %u format specifier.
Though the quads of an IP address literally are bytes, they can
be left as an int to pass to String.format. This allows room for
sign bits, so intToInetString(0x0101a8c0) returns "192.168.1.1"
--------
adds JUnit dependencies and basic gradle support to run unit tests,
and a test for DnsConfig.intToInetString().
--------
> DnsConfig: don't use signed bytes when printing.

- cmd/tailscale/backend.go
- cmd/tailscale/main.go
- cmd/tailscale/ui.go
- go.mod
- go.sum
Includes netaddr -> netip changes.
main.go getInterfaces still uses netaddr as it needs to return a net.IPNet (we'd need to add a new implementation in https://github.com/tailscale/tailscale/blob/7c671b0220a5a42303dd68c8b63a5baedcce885e/net/interfaces/interfaces.go#L110 to handle a different type).
> go.mod: update from OSS.

- cmd/tailscale/main.go
- cmd/tailscale/ui.go
This has never worked well. I think we'd need to periodically re-check
link state, and possibly hook up a generate_204 function, to make this
really work.
Fixes https://github.com/tailscale/tailscale/issues/5422
> UI: remove "No internet connection"

- .github/licenses.tmpl
- .github/workflows/go-licenses.yml
Also ignore tailscale.com package (and add directly to template) and remove branch-suffix. This aligns android with other go-license workflows.
> .github/actions: signoff go-licenses commits

- cmd/tailscale/main.go
- cmd/tailscale/ui.go
Add "about" menu item in both the logged out and logged in menus.  About dialog shows Tailscale version and link to URL with open source licenses.
The version entry in the about dialog does duplicate the version at the top of the logged-out menu.  Maybe that's okay?  Maybe we remove it from the menu?  I seem to recall it was really only there so that the menu wasn't completely empty if you hadn't yet activated the debug menu?  We could also remove it from the About dialog; I just added it because it seemed to make sense.
Updates tailscale/corp#5780
> android: add about dialog with license link

- android/build.gradle
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/IPNService.java
Required for apps to update in the Play Store after November 1.
This requires:
- manifest must specify if Intents are exported.
- PendingIntent must declare FLAG_IMMUTABLE or MUTABLE
> build.gradle: update to SDK31

- cmd/tailscale/main.go
- cmd/tailscale/ui.go
With the Fast User Switching support in Tailscale 1.34, it is no longer necessary (nor sufficient) to exit and restart the app, as the settings are saved upon first connection.
Therefore:
- do not restart the app after changing the control URL, just go back to the authentication screen.
- call `ipn/ipnlocal/local.go:Start()` to reinitialize the backend using the new auth URL.
Fixes https://github.com/tailscale/tailscale/issues/6671
> cmd/tailscale: fix alternate ControlURL handling.

- cmd/tailscale/ui.go
Prior to https://github.com/tailscale/tailscale-android/pull/73/, the exit node status pane was set to a background color using:
paint.Fill(gtx.Ops, bg)
paint.Fill() is documented to fill the entire clipped area. It assumes that one has already applied a clip area... but no clip area had been set in this code path.
As far as I can tell, that this worked prior to pull #73 was a bug, something had a side-effect of setting a clipping rectangle.
We updated to the head of the Gio repo, which apparently fixed that bug. After pull #73, the paint.Fill() painted the entire app window.
Fix this using a stacked layout. A color filled widget is the lower layer, and will expand to the size of the widget sitting atop of it.
Fixes https://github.com/tailscale/tailscale/issues/6873
Signed-off-by: Denton …
> ui: Fix background color of exit node status.

- Makefile
- android/build.gradle
- go.mod
- go.sum
Upstream Gio fixed https://todo.sr.ht/~eliasnaur/gio/473, which we run into in https://github.com/tailscale/tailscale/issues/7255
https://github.com/tailscale/tailscale has moved to Go 1.20
- update go.mod to go 1.20
- go mod tidy -compat=1.20
- update go4.org/unsafe/assume-no-moving-gc
Skip over the build numbers used for 1.36.x
Fixes https://github.com/tailscale/tailscale/issues/7255
> go.mod: update Gio, finish Go 1.20 support

- android/src/main/java/com/tailscale/ipn/IPNService.java
Needed for LAN discovery of Chromecast devices.
Fixes https://github.com/tailscale/tailscale/issues/3636
> IPNService: add Chromecast to the apps allowed to bypass the VPN.

- Makefile
We build with the tailscale Go toolchain, so we should pass in the build tag that indicates that it's safe to use functionality contained within it.
Updates tailscale/corp#9230
> Makefile: add tailscale_go to the set of build tags

- cmd/tailscale/main.go
This adds the currently used (if any) exit node to the persistent Tailscale notification.
I was going to open a new FR for this, but found that the request has been made before tailscale/tailscale#4642 (over a year ago) and (imo incorrectly) closed as a duplicate of tailscale/tailscale#4383. 
Below is a screen snippet of what this PR adds. Note that the exit node that I'm using here is actually called `tailscale` and may have been a bit poorly chosen for demonstration purposes.
> Exit node in notification

- cmd/tailscale/backend.go
In 00a42702cb4e I bumped go.mod and adjusted the API, but only tested that it compiled & tests (hah) passed.
I forgot this line. I still haven't tested this, but can't be worse! :)
Fixes https://github.com/tailscale/tailscale-android/commit/00a42702cb4ee29c02514744048f35a270f809ed#commitcomment-112642284
> cmd/tailscale: fix regression from earlier commit

- Makefile
I'm not sure why [[:digit:]] worked before but not now (BSD vs GNU sed maybe?), but since we already have the old VERSIONCODE, just replace it directly. Also cleanup the android/build.gradle.bak file.
> Makefile: fix versionCode replacement and cleanup

- Dockerfile
Use a slightly more current version of Java (jdk-11), as well as more recent versions of Android command line tools, build tools, and Go.
This was the dockerfile Charlotte used for the 1.44.0 release today, so I'm pretty confident it works.
> Dockerfile: update build tools in dockerfile

- cmd/tailscale/main.go
> cmd/tailscale: don't render ShareeNode peers

- cmd/tailscale/main.go
Currently, if the notification (ipn.Notify) has a nil Prefs, the hostname defaults to localhost
Fixes #7875
> cmd/tailscale: if first notification, set hostname even if prefs is nil

- android/build.gradle
Required to build unstables and for the 1.46 release process.
> android: increment versionCode to 170

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
-Update Gradle version
-Replace jcenter() with mavenCentral() because of jcenter deprecation -Use testImplementation instead of the obsolete testCompile
Fixes #12997
Tested with docker
> android: update gradle version

- version/tailscale-version.sh
If the developer has used `go mod vendor` or `go work use ../tailscale` then the version script was returning "tailscale.com" instead of hitting the error case.
This now makes the outcome with the Makefile slightly worse, which needs to be fixed up next.
> version: fix result from tailscale-version.sh when not using a git source

- .gitignore
- Dockerfile
- Makefile
- README.md
- Teach Makefile to install an Android SDK and the components we need
- Make Dockerfile delegate to Makefile for Android SDK setup
- Detect Android Studio and other known SDK paths, and use them if found.
- Update documentation to more consistently point to Android Studio & make.
- Add a task that checks for the SDK components and produces a useful error.
- Build an APK by default.
- Allow TOOLCHAINDIR to be passed in, and strip the first go/ component
so that it is the path a user would expect.
> Makefile,Dockerfile,README.md: improve build dependency setup and documentation

- android/src/main/java/com/tailscale/ipn/App.java
- android/src/main/java/com/tailscale/ipn/IPNService.java
- android/src/main/java/com/tailscale/ipn/StartVPNWorker.java
Added a check to check if the VPN is connected before triggering the connect behaviour.
Was introduced in https://github.com/tailscale/tailscale-android/pull/87
Fixes: https://github.com/tailscale/tailscale/issues/8013
> Prevent connecting loops when using connect intent more than once

- Makefile
Fixes tailscale/tailscale#8799
> Makefile: fix escaping when detecting JAVA_HOME on macOS

- .github/workflows/build.yml
- Dockerfile
- android/build.gradle
- android/gradle.properties
Another upgrade recommended by Android Studio, again this is just upgrading the build tooling, and not yet changing any of the runtime side dependencies or behaviors.
We switch from jcenter to mavenCentral as advised in the build output, as jcenter has shutdown.
> android: upgrade gradle plugin runtime to 8.1

- cmd/tailscale/main.go
We have been getting into routing loops due to the timing of when we bind sockets on starting the tailscale app. At this point, we do not have access to `VpnService.protect()` and are unable to protect the magicsock sockets, which causes a routing loop issue until we forcibly rebind about 10 minutes into the service being started.
This change rebinds when we detect that the protect function is no longer nil, and restores connectivity.
Updates tailscale/corp#13814
> cmd/tailscale: rebind magicsock.Conn onConnect

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/App.java
"bluetooth_name" cannot be accessed after SDK 31, remove it from getUserConfiguredDeviceName().
Fixes https://github.com/tailscale/tailscale/issues/8955
> build.gradle: update targetSdkVersion to 33.

- Makefile
The Android SDK tools go into a CPU spin if $JAVA_HOME is empty and never complete. This may occur if you have only an incomplete Android SDK, and no Android Studio install, wherein we do not find an Android JAVA_HOME.
> Makefile: avoid setting empty JAVA_HOME to avoid SDK tools bugs

- cmd/tailscale/backend.go
- cmd/tailscale/ui.go
- go.mod
- go.sum
These changes pick up the latest OSS and fixes the build.
I've split it into two commits so that I can `cherry-pick` the breakage fix onto 1.50.0.
> Build fixes

- version/tailscale-version.sh
5ca195b1097fad0b750e1ac04bdd49ed3313c123 changed the shell code to determine the OSS module version:
-mod_version=${go_list##* }
+mod_version=${go_list#tailscale.com}
The intent is fine but the original code also consumed a whitespace from the go.mod content:
tailscale.com v1.52.0
original: "v1.52.0"
updated:  " v1.52.0"
At least for me, "make tag_release" no longer works:
error: pathspec ' v1.54.0' did not match any file(s) known to git
Note the extra space at the start of the pathspec.
It is apparently not broken for everyone, possibly related to versions of other tools I have installed like maybe git.
I don't want to just put the whitespace trimming back the way it was, that seems fragile. Instead, quote ${mod_version} in a way which won't be sensitive to extra whitespace.
> version: handle whitespace in ${mod_version}

- android/src/main/java/com/tailscale/ipn/App.java
We accidentally removed this in the big connectivity monitor fix.
Updates tailscale/tailscale#10107
> Record DNS search domains as well as nameservers.

- cmd/tailscale/main.go
- cmd/tailscale/ui.go
This change provides minor improvements to the exit node menu when there are location based exit nodes present. It will ensure that non location based exit nodes are displayed at the top of the list, followed by a the best node for a country/city combination, and followed by all location based exit nodes.
Updates tailscale/tailscale#9421
> cmd/tailscale: improve exit node menu for location based exit nodes

- cmd/tailscale/ui.go
This change stops us from clogging up the main UI view with location based exit nodes, which can be in their hundreds. They will still appear in the exit node UI.
Updates tailscale/tailscale#9438
> cmd/tailscale: do not show location based exit nodes in main view

- android/src/main/java/com/tailscale/ipn/IPNReceiver.java
- android/src/main/java/com/tailscale/ipn/QuickToggleService.java
- cmd/tailscale/callbacks.go
Fix for Android quick settings tile - based on new intents `com.tailscale.ipn.CONNECT_VPN` and `com.tailscale.ipn.DISCONNECT_VPN` from https://github.com/tailscale/tailscale/issues/3547
> Fixes Android quick settings tile - issue #2646

- cmd/localapiclient/localapiclient.go
- cmd/tailscale/backend.go
- cmd/tailscale/main.go
- go.sum
-Create a custom http.ResponseWriter whose responses can be read and in the future, sent to Java/Kotlin via JNI
-Make http request and call localapi directly
The purpose of this change is to test out swapping an existing feature's implementation for the new pattern of using localapi. I added a global channel for the bug report in order to contain the scope of this change to just this. 
Updates #10992
> cmd/tailscale/main: use localapi for generating bug report

- cmd/tailscale/main.go
Currently the custom control server is not applied on start. To remedy this, check the stored preference and if they differ issue an event to switch to the correct backend server.
> cmd/tailscale/main: apply custom control server on first start

- cmd/tailscale/backend.go
In the latest tailscale.com, netstack.Create has a new parameter that must be supplied.
> cmd/tailscale: pass nil TailFSForLocal to netstack.Create

- android/src/main/java/com/tailscale/ipn/App.java
- android/src/main/java/com/tailscale/ipn/IPNService.java
- cmd/tailscale/callbacks.go
- cmd/tailscale/main.go
-If a ConnectEvent is received before the first notification, (as happens when a connection is attempted due to Always-on after device reboot) create state.Prefs.
-Create an intent to start the VPN worker in the case of an always-on intent received on device reboot
-Rename onConnect channel to onVPNRequested, since this isn't doing the actual connecting
Fixes https://github.com/tailscale/tailscale/issues/2481
> cmd/tailscale, tailscale/ipn: fix alway-on VPN

- cmd/tailscale/backend.go
- cmd/tailscale/main.go
When user signs in or starts the session, check and restore the following settings if set previously: 
- allow LAN access 
- use exit node
- use custom login server
Fixes tailscale/tailscale#10748
> cmd/tailscale/main: restore persisted settings

- android/src/main/java/com/tailscale/ipn/App.java
- cmd/tailscale/main.go
- cmd/tailscale/syspolicy_handler.go
Adds a syspolicy handler for Android in cmd/tailscale. This allows the Go code to use the syspolicy package to read values set by a system administrator using the Android RestrictionsManager.
Out of the box, this adds supports for a number of MDM policies that are fully implemented on the Go side, such as `ExitNodeID` (forced exit node functionality).
> mdm: add Android syspolicy handler

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/localapi/LocalAPIClient.kt
- android/src/main/java/com/tailscale/ipn/ui/localapi/LocalAPIRequest.kt
- android/src/main/java/com/tailscale/ipn/ui/model/IpnState.kt
- android/src/main/java/com/tailscale/ipn/ui/model/NetMap.kt
- android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/java/com/tailscale/ipn/ui/service/IpnManager.kt
- android/src/main/java/com/tailscale/ipn/ui/service/IpnModel.kt
- android/src/main/java/com/tailscale/ipn/ui/service/PrefsEditor.kt
- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
- android/src/main/java/com/tailscale/ipn/ui/util/Styles.kt
- android/src/main/java/com/tailscale/ipn/ui/util/TimeUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
updates tailscale/corp#18202
updates ENG-2854
Adds a basic settings screen.  This isn't correctly localized, but that's on the way.
Adds the required hooks to edit prefs via localAPI.
Adds basic but incomplete login/logout flow.
Fixes the sorting of nodes on the main screen and fixes the proper display of your current node details.
> android: add settings screen and login flow

- android/src/main/java/com/tailscale/ipn/App.java
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- android/src/main/java/com/tailscale/ipn/ui/service/IpnManager.kt
updates tailscale/corp#18202
updates ENG-2849
Implements the basic data model for supporting MDM to allow us to add the hooks in the UI.
> mdm: implement initial data structure to read from Android Restrictions Manager

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/Links.kt
- android/src/main/java/com/tailscale/ipn/ui/service/IpnManager.kt
- android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/BugReportViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/res/values/strings.xml
updates tailscale/corp#18202
fixes ENG-2876
Adds the bug reporting view.  Functional, but not properly styled.
Moves the various link URLs to a constants file and corrects link-opening in both but reporting and the settings screen.
Adds an AboutView with app icon and same content as the iOS version.
> android: implement the bug reporting and about screen and localize

- android/src/main/java/com/tailscale/ipn/App.java
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/res/values/strings.xml
- cmd/tailscale/main.go
- cmd/tailscale/syspolicy_handler.go
Adds a view to see the currently set MDM settings, we're going to need this to debug actual MDM integrations more effectively.
Adds a syspolicy handler for Android in cmd/tailscale. This allows the Go code to use the syspolicy package to read values set by a system administrator using the Android RestrictionsManager.
Out of the box, this adds supports for a number of MDM policies that are fully integrated on the Go side, such as `ExitNodeID` (forced exit node functionality).
Signed-off-by: Jonathan Nobels <jonathan@tailscale.com>
Signed-off-by: Andrea Gottardo <andrea@gottardo.me>
> ui: add view to debug MDM settings and add the syspolicy handlers

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/util/AvatarLoader.kt
- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
- android/src/main/java/com/tailscale/ipn/ui/util/TimeUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/BugReportViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/res/values/strings.xml
fixes ENG-2852
We'll now load and display the user avatar in the main and settings screen similar to iOS.
The MutableStateFlows in the view models are cleaned up to match the style in the IPNModel.
The peer search was blowing up due to some null references and not properly removing the self category if there were no matches.
Fixed a bunch of missing localizations.
> android: adds support for user avatars and some general cleanup

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/res/values/strings.xml
- Adds the "Managed by OrganizationName" view we currently offer on iOS.
- Hides the MDM settings debug pane on non-debug builds.
- Refactored SettingsViewModel to take an `IpnManager` instead of an `IpnModel` (@barnstar, let me know whether this makes sense given your future plans)
> ui: add ManagedByView, hide MDMSettingsView on non-debug builds

- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
Switch to LazyColumn so we're not redrawing the entire list.
Modify the search logic so we're searching progressively and doing all of the sorting and categorization up front on netmap changes.
> android: optimize peer search

- android/src/main/java/com/tailscale/ipn/ui/util/ComposableStringFormatter.kt
- android/src/main/java/com/tailscale/ipn/ui/util/DisplayAddress.kt
- android/src/main/java/com/tailscale/ipn/ui/util/Styles.kt
- android/src/main/java/com/tailscale/ipn/ui/util/TimeUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/PeerDetailsViewModel.kt
- android/src/main/res/values/strings.xml
Localizations and some logical cleanup for formatting "in x time_unit" strings for the node details.
Removes the "starting" screens and shows the peer details, search and exit node picker even when the VPN isn't running since we can do this on Android.
Moves the ComposableStringFormatter to a central location since it'll be used in a number of places.
Fixes showing your current node as connected (when you're connected) and shows the magicDNS domain names in the peer details.
Signed-off-by: Jonathan Nobels <jonathan@tailscale.com>
> android/ui: fix time formatting strings and main view states

- android/build.gradle
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/App.java
- android/src/main/java/com/tailscale/ipn/IPNReceiver.java
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/java/com/tailscale/ipn/ui/theme/Color.kt
- android/src/main/java/com/tailscale/ipn/ui/util/Styles.kt
- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/Buttons.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ErrorDialog.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/UserSwitcherViewModel.kt
- android/src/main/res/values/strings.xml
Updates ENG-2875
Fixes ENG-2863
Adds everything we need to do fast user switching and support multiple accounts.
Some work here to make the settings rows and a few other composables common and reusable.
Added quick but incomplete support for requesting VPN permissions in the new activity.
Correct the focus and clear behaviour on the search bar and corrected the connected in state of SelfNode.
> android: implement fast user switching

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
The actual requesting of VPN permissions was lost in a rebase. This change should prompt you on start.
> android: request VPN permissions on launch

- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
Several API endpoints will return an empty body on success which was throwing a null pointer exception when we tried deserialize it.
> android: fix NPE for empty localAPI response bodies

- Makefile
No need to build into /tmp, the go cache will handle this for us, we can just use go run.
> Makefile: cleanup go mobile builds some

- Makefile
- go.mod
- go.sum
- go.toolchain.rev
- tool/go
- This tool/go does not currently invoke gocross, as there's more work to do in gocross to be fully compatible with gomobile.
- Use GOBIN to target the output destinations for gomobile and gobind.
- Remove the old toolchain targets from the Makefile.
- Use ~/.cache/tailscale-go, like the OSS repo does.
- Introduce go.toolchain.rev as we have in the OSS repo, and update it in the bumposs task.
> *: introduce tool/go following our common pattern

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/Peer.java
- android/src/main/java/com/tailscale/ipn/VPNServiceBuilder.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- libtailscale/callbacks.go
- libtailscale/interfaces.go
-Move most of prepare and establish VPN logic out of Go into Android 
-Fix prepareVPN argument to use request codes to differentiate sign in and prepare VPN 
-Fix missing adapter implementation (setMtu)
> android: fix vpn

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TintedSwitch.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/res/values/strings.xml
Adds back navigation to all of the headers.
Corrects all padding and some colours
Adds separators to the device list
Adds the Compat theme so we don't have the black top and bottom bars. Removes all of the chevrons.
Other minor tweaks
> android/ui: address preliminary design feedback (#227)

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/util/FeatureStateRepresentation.kt
- android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/FeatureStateView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/DNSSettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/res/values/strings.xml
Updates ENG-2990
This PR adds a DNS Settings view with the same functionality and items as the iOS one. It also moves the 'Use Tailscale DNS Settings' item out of the main settings view into the detail view.
> android: add DNS Settings view

- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
Closes #ENG-2988
It turns out the backend already cycles through states correctly when doing fast user switching. This change just makes sure that if a machine has been deauthorized, we prompt the user to login again.
> android: show login button when state == Ipn.State.NeedsLogin

- android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/DNSSettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
- android/src/main/res/values/strings.xml
Updates ENG-3011
Just like on iOS, we should show a switch at the bottom of the exit node picker to toggle the `ExitNodeAllowLANAccess` preference.
> android: add ExitNodeAllowLANAccess toggle in exit node picker

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
- android/src/main/java/com/tailscale/ipn/ui/model/FileTransfer.kt
- android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TaildropView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/TaildropViewModel.kt
- go.mod
- go.sum
Helps track status of transfers.
Updates #ENG-2868
I tested that I can initiate multiple concurrent transfers to the same peer. The status tracking correctly tracks status for the last initiated transfer, and all prior transfers still succeed (though their status is not tracked).
> android/ui: add transfer ID to outgoing file transfers

- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
This makes sure only the relevant UI control flashes on click
> android/ui: change click target for exit node picker

- android/src/main/java/com/tailscale/ipn/App.kt
- libtailscale/backend.go
- libtailscale/callbacks.go
- libtailscale/interfaces.go
- libtailscale/tailscale.go
Implements direct mode support for incoming taildrop files.  None of the localAPI endpoints are implemented here but this will get taildrop files to the right places.
> android/taildrop: support direct mode for incoming taildrop

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/DNSSettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/UserSwitcherViewModel.kt
@sonovawolf noticed that the Settings view was slow to load. In the logs, I was able to see these kinds of warnings when opening the settings view, a warning that so far I'm not seeing anywhere else.
```
Choreographer  I  Skipped 38 frames!  The application may be doing too much work on its main thread.
```
This PR does a couple of things to address this:
1. The most impactful is to refactor MDMSettings to use StateFlows and only call RestrictionsManager once to initialize those (and do so outside of the UI thread)
2. Simplifies the settings model and takes out some StateFlows and corresponding `collectWithState()` calls
The first part is implemented in reusable fashion as the extension method `ViewModel.launchForInit`
> android/ui: speed up loading of SettingsView

- android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
hides the mullvad nodes (basesd on their Name) in the peers list.  This differs slightly from the iOS logic where we use the Location property, but it feels like a better approach since Location is optional in the HostInfo and may not always be present.
> android/ui: hide mullvad exit nodes in peer list

- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
- android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ErrorDialog.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/UserSwitcherViewModel.kt
- android/src/main/res/values/strings.xml
fixes ENG-2871
Adds a menu option under the FUS for logging in with your custom control server.  Follows the general pattern used on macOS.
> android/ui: add support for logging in using a custom control server

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
For our initial release, we will only support landscape on large screen devices (tablets, chromebooks).
Tested on a tabletizable chromebook and a variety of simulators and this seems to be a decent compromise until we have fully landscape capable layouts.
> android/ui: disable landscape on small screen devices

- android/build.gradle
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/res/values/splash.xml
Updates the splash screen to the modern themed jetpack compose variant.
> android/ui: add compose-style splash screen

- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
This moves the logged-in-user to global state (which is is) and sets it immediately when you switch tailnets.  On failure, we will set things back to the prior user.
This fixes the issue of seeing the "old" user while the transition is happening.
> android/ui: show the switching-to user immediately on FUS switch

- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/res/values/strings.xml
Updates the exit node stop button to 'stop' instead of 'disable' pending the required back end changes to remember the preferred exit node.
> android/ui: change exit node disable string to 'stop'

- Makefile
Reduces total size for 4 architectures from 59517778 to 33420646
Before change
```
➜  tailscale-android git:(ox/apksize) ✗ ls -l android/libs/libtailscale.aar
-rw-r--r--@ 1 percy  staff  59517778 Apr  3 14:40 android/libs/libtailscale.aar
```
After change
```
➜  tailscale-android git:(ox/apksize) ✗ ls -l android/libs/libtailscale.aar
-rw-r--r--@ 1 percy  staff  33420646 Apr  3 14:49 android/libs/libtailscale.aar
```
> android/ui: strip DWARF debug information from libtailscale

- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
NoState is now treated similar to starting for the on/off switch (which matches behaviour of the string)
This makes the switch transition to "on" immediately.  "null" is where we start.
> android/ui: treat NoState similar to Starting

- android/src/main/java/com/tailscale/ipn/ui/view/RunExitNodeView.kt
- android/src/main/res/values/strings.xml
Restyle the run as exit node screen per UX
> android/ui: restyle the run as exit node screen

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
We're starting Notifier in App so that states are available outside of MA lifecycle.
> MainActivity: remove redundant Notifier start/stop

- cmd/tailscale/backend.go
- go.mod
- go.sum
- libtailscale/backend.go
- libtailscale/net.go
- libtailscale/tailscale.go
- libtailscale/vpnfacade.go
This avoids reconfiguring the VPN both when routes changed and then again when DNS changed.
Updates tailscale/corp#18928
Depends on https://github.com/tailscale/tailscale/pull/11623
> android: only reconfigure VPN when ready

- android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/DNSSettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/UserSwitcherViewModel.kt
The first commit fixes the proximate [issue](https://github.com/tailscale/corp/issues/18983). The second commit just generally cleans up how we do settings. Having them as data unnecessarily complicated things and kept us from doing more normal state management.
> Stop treating settings as data

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
- android/src/main/java/com/tailscale/ipn/ui/util/AndroidTVUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/IntroView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/LoginQRView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/LoginQRViewModel.kt
- android/src/main/res/values/strings.xml
fixes tailscale/corp#18956
fixes tailscale/corp#18964
Adds a letterboxing effect as a temporary measure to make the UI a bit more usable on AndroidTV. Fixes a few navigation peculiarities specific to TV (notably, there some padding on the user avatar so you can see when it's highlighted). Pops a QR code on AndroidTV where we have no browser to complete the flow.
> android/tv: reduce layout width and fix navigation

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
Fixes tailscale/corp#19070
If the activity hadn't yet been created, we can still get an onIntent which was assuming the navController had been instantiated.  Switched that to and optional so that we can null check it.
> android/ui: prevent navigation before we've added content

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- libtailscale/interfaces.go
- libtailscale/syspolicy_handler.go
- libtailscale/tailscale.go
port over https://github.com/tailscale/tailscale-android/pull/199 from cmd/tailscale and legacy_android to libtailscale and android/
fix issue where we were creating MDMSettings every time we were retrieving policy settings 
> ui: port syspolicy handler code to new app

- .gitignore
- Makefile
- android/build.gradle
- android/src/androidTest/kotlin/com/tailscale/ipn/MainActivityTest.kt
- android/src/androidTest/kotlin/com/tailscale/ipn/TestUtil.kt
The test verifies that one can log in via the UI and hit hello.ts.net.
> android: added smoke test

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
- android/src/main/java/com/tailscale/ipn/ui/util/DisplayAddress.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/res/values/strings.xml
Fixes corp#19119
Adds a variation on the ConnectView to render a header and explainer text for the NeedsMachineAuth state.  A button to take you directly to the admin page is presented if you are an admin.
> android/ui: handle NeedsMachineAuth state

- android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
Fixes tailscale/tailscale#11701
We should not show a key expiry warning if the KeyExpiry is a zero-value time.Time
> ui: don't show key expiry warning if key doesn't expire

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
Fixes tailscale/tailscale#11716
The implementation of the syspolicy handler on Android was incomplete. As explained in the comments, a syspolicy handler should return a `syspolicy.ErrNoSuchKey` error when a value is not defined for a given key: 
https://github.com/tailscale/tailscale/blob/65f215115f0290502600d638557bf9b0f60aa6a6/util/syspolicy/handler.go#L27
The Android handler was instead returning an empty string.
When attempting to log in with a custom coordination server, since we were not returning `syspolicy.ErrNoSuchKey`, the caller into the syspolicy package was always fetching an empty string from the MDM setting instead of using the default value `p.ControlURL`:
https://github.com/tailscale/tailscale/blob/65f215115f0290502600d638557bf9b0f60aa6a6/ipn/prefs.go#L665
The fallback …
> mdm: throw ErrNoSuchKey when value not defined in Android syspolicy handler

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ErrorDialog.kt
- android/src/main/java/com/tailscale/ipn/ui/view/IntroView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/LoginQRView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
Updates corp#19117
This adds @Previews for many of the primary views.  We can expand upon this over time to include different data sets, states, etc.  Some are not included here due to issues with dependency injection/singletons, lack of fake data etc... But this gets the ball rolling.
The ErrorDialogs were not wrapped in the AppTheme either - so one bug fixed.
> android/ui: improve dev QOL by adding support for compose previews

- android/src/main/java/com/tailscale/ipn/ui/view/AboutView.kt
Fixes tailscale/corp#19171
This came up in beta users feedback. We should let people copy their current version number, it makes it easier to report what build they're running when filing a bug.
> ui: allow copying version number by tapping on it

- android_legacy/src/main/AndroidManifest.xml
- android_legacy/src/main/java/com/tailscale/ipn/App.java
- android_legacy/src/main/java/com/tailscale/ipn/IPNActivity.java
- cmd/tailscale/main.go
This should fix https://github.com/tailscale/tailscale/issues/10104.
I recorded a screencast of this working on my emulator. I am happy to send it to someone at Tailscale privately, if needed.
From Android's docs:
> Android 13 (API level 33) and higher supports a [runtime permission](https://developer.android.com/guide/topics/permissions/overview#runtime) for sending [non-exempt](https://developer.android.com/develop/ui/views/notifications/notification-permission#exemptions) (including Foreground Services (FGS)) notifications from an app: [POST_NOTIFICATIONS](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS). This change helps users focus on the notifications that are most important to them.
Ref: …
> Restore persistent VPN status notification in Android 13+

- .github/licenses.tmpl
The android app no longer uses gioui.
> .github/licenses: remove gioui from license list

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- libtailscale/interfaces.go
- libtailscale/syspolicy_handler.go
Updates tailscale/corp#19459
Allows the Go backend to read string array values stored in the Android RestrictionsManager.
> mdm: add string array support in Android syspolicy_handler

- android/src/main/java/com/tailscale/ipn/QuickToggleService.java
startActivityAndCollapse(Intent) is deprecated for >= API 34, use startActivityAndCollapse(PendingIntent) instead
Fixes tailscale/corp#19546
> QuickToggleService: use undeprecated startActivityAndCollapse

- android/src/main/java/com/tailscale/ipn/App.kt
- libtailscale/backend.go
- libtailscale/callbacks.go
- libtailscale/net.go
Use Android API to pass interface name to Tailscale on network updates
Pull in OSS changes to include https://github.com/tailscale/tailscale/pull/11784 
Fixes tailscale/corp#19215
> android: pass interface name to go

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/QuickToggleService.java
Fixes ENG-3443
As discussed during design review, provides a "Connected" / "Not connected" subtitle in the Tailscale quick tile.
Also drops unnecessary SDK version checks in App.kt.
> ipn: provide subtitle in QuickToggleService

- libtailscale/syspolicy_handler.go
Let's make these log lines a bit less scary when MDM is not being used to enforce a value.
> mdm: improve logs when keys are undefined

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/QuickToggleService.java
- android/src/main/java/com/tailscale/ipn/StartVPNWorker.java
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
-Get rid of unused stopVPN() function
-Get rid of unused ACTION_STOP_VPN intent handling; this is redundant with DISCONNECT_VPN intent -Tile active state should only depend on ipn state, and not the results of editing the prefs with wantRunning set. It should be active iff ipn.State > Stopped
Fixes tailscale/tailscale#11920
> android: fix Quick Settings tailscale

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/res/values/strings.xml
-When connected, tapping on the notification disconnects 
-When disconnected, tapping on the notification connects 
-Navigate to system notifications instead of app info when tapping on 'Notifications' 
-Add text to notification permissions request explaining that the persistent notification is off by default
-Clean up unused notification channel and methods
-Follow up will be to update logo depending on connection status
Fixes tailscale/tailscale#10104
> android: add persistent notification with VPN status

- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
- android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
Fixes tailscale/corp#19743
Adds the hooks for the various MDM settings applicable to Android with the exception of the keyExpirationNotice which we'll handle separately.
> android/ui: add mdm hooks

- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
This allows us to precisely set the options we need during login and avoid wiping away defaults like AllowSingleHost.
Updats tailscale/tailscale#11731
> android: use EditPrefs instead of passing UpdatePrefs to start

- android/src/main/AndroidManifest.xml
This is a workaround for tailscale/corp#19860 until the root cause can be sorted out.
Updates tailscale/corp#19860
> android: temporarily remove quick settings tile

- android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
Fixes tailscale/corp#19881
Exit node picker button is now grey-200 in light mode and grey-700 in dark mode for the disabled state.
After:
> android/ui: fix theming for the exit node picker button

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
> android: only navigate to main if navController is initialized

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNReceiver.java
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/Peer.java
- android/src/main/java/com/tailscale/ipn/QuickToggleService.java
- android/src/main/java/com/tailscale/ipn/StartVPNWorker.java
- android/src/main/java/com/tailscale/ipn/StopVPNWorker.java
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/java/com/tailscale/ipn/ui/util/AndroidTVUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/res/values/strings.xml
https://github.com/tailscale/tailscale-android/pull/358 updated the Quick Settings tile to only depend on ipn state. This was only partially correct in the sense that we made changes to only check for whether the state was > stopped and not whether Tailscale was on.
This checks for two states, whether Tailscale is on, and whether the tile is ready to be used. The former requires ipn state to be >= Starting, and the latter checks whether ipn state is > RequiresMachineAuth. Tile readiness determines whether an intent is to open MainActivity or whether an intent to connect/disconnect VPN is sent. Whether Tailscale is on or off determines whether the tile status is active or not.
Updates tailscale/tailscale#11920
> android: fix quick settings tile status

- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
https://github.com/tailscale/tailscale-android/assets/135075563/6c50e05f-93ba-4929-951e-2cca0054627f
Toggle should be on when user transitions from NoState -> Starting, but not when the user is in NoState. This change uses a placeholder string "--" when the user is in NoState.
Fixes tailscale/corp#19961
> MainViewModel: treat NoState -> Starting as starting

- android/src/main/java/com/tailscale/ipn/ui/util/LoadingIndicator.kt
- android/src/main/java/com/tailscale/ipn/ui/view/BugReportView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/CustomLogin.kt
- android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/LoginQRView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MullvadExitNodePickerList.kt
- android/src/main/java/com/tailscale/ipn/ui/view/RunExitNodeView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TaildropView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/TaildropViewModel.kt
"by stateFlow" is syntactic sugar for" = stateFlow.value" and is more idiomatic.  There should be no functional difference here.
> android/ui: use compose getValue syntactic sugar consistently

- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
Updates tailscale/tailscale#12148
There was a small bug where we weren't rechecking the vpn permissions so the FUS would never show.  We'll now do that in the view model base case on initialization and again on vpn-enable.
> android/ui: unhide accounts if VPN is prepared

- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/ExitNodePickerViewModel.kt
> ExitNodePicker: don't allow run as exit node while using exit node

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
https://github.com/tailscale/tailscale-android/pull/398 introduced a bug where we were not calling startVPN after getting (or confirming) VPN.prepare permissions This resulted in the VPN not being turned on after logging in for the first time
Updates tailscale/tailscale#12148
> android: start VPN after preparing VPN

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
Follow-up to https://github.com/tailscale/tailscale-android/pull/389
Use foreground notifications only when the service was started as a foreground service
> android: make disconnected notification non-foreground

- Makefile
- docker/DockerFile.amd64-build
- docker/DockerFile.amd64-shell
Updates tailsale/corp#19670
Added a dockerfile where can run full release build in addition to  dropping into a shell.
The build will now look for JKS_PASSWORD in the environment for completing the signing step without user interaction.
Several smaller recipes added to the makefile for building the docker builder image, running and cleaning it up.
> android/docker: update makefile and dockerfile for build automation

- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
fixes tailscale/corp#12431
The share extension was initializing it's own Notifier.  It does not need to, it simply needs to ensure the shared app instance has been initialized and a suitable notifier instance will already be running.
> android/ui: remove Notifier initialization on ShareIntent

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNReceiver.java
- android/src/main/java/com/tailscale/ipn/UseExitNodeWorker.kt
- android/src/main/res/values/strings.xml
Closes https://github.com/tailscale/tailscale/issues/8143. I map friendly labels from intent extras to tailscale node IDs, with empty string or not specifying the exitNode intent extra as the "no exit node" action. When an error is encountered, we will push a notification with a friendly message to the status notification channel. The tasker syntax I tested with locally is:
Action: `com.tailscale.ipn.USE_EXIT_NODE`
Package: `com.tailscale.ipn`
Class: `com.tailscale.ipn.IPNReceiver`
Target: Broadcast Receiver
Extra: `exitNode:exitNodeLabelOrEmpty`
Extra: `allowLanAccess:trueOrFalse`
> Implement USE_EXIT_NODE intent

- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
fixes tailscale/corp#20846
Adds searching by IP to android, matching the existing iOS behavior.
> android/ui: support searching for node by IP address

- android/src/main/java/com/tailscale/ipn/ui/util/ClipboardValueView.kt
- android/src/main/java/com/tailscale/ipn/ui/util/Lists.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
updates tailscale/corp#20930
This addresses several issues with AndroidTV navigation,
all possible causes of the 1.68 rejection (the exact reasons
are unknown - we're await clarification).  But in the mean time:
The search bar is removed until we have a better solution
for D-pad navigation.   This should be addressed when we
switch to a less customized component.   Full replacement of
the search functionality is beyond the scope of this change.
The back button will now automatically request the focus on AndroidTV 
devices by default so there is always at least one element focussed.
Views with clipboard support are disabled since this was 
not functional (nothing was getting copied to the clipboard).
View with embedded links are removed since these
require touch support and a browser.
> android/ui: fix AndroidTV navigation issues

- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
updates tailscale/corp#20930
To address review concerns regarding the toggle being unresponsive with the d-pad.  We'll now open the QR login screen on android TV if you toggle the VPN when we're in the NeedsLogin state.
> android/ui: open login screen on toggle

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/model/Health.kt
- android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/HealthNotifier.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/res/values/strings.xml
This PR adds support for notifying the user when health warnings are sent down coming from LocalAPI. We remove duplicates and debounce updates; then deliver a notification for each health warning are they are sent down. Just like on macOS, notifications are removed when a Warnable becomes healthy again.
Notifications are delivered on a separate notification channel, so they can be disabled if needed.
> ui: deliver health notifications to user

- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
updates tailscale/corp#20930
Google reviewers were unhappy that there was a non-actionable label for AndroidTV when before login had happened, so that has been removed.
> android/ui: remove switch and status label on TV before login

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/util/InstalledAppsManager.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SplitTunnelAppPickerView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SplitTunnelAppPickerViewModel.kt
- android/src/main/res/values/strings.xml
Updates tailscale/tailscale#6912
This PR is a little QoL improvement for our Android users. It adds UI and models that provide the ability to add/remove apps which should be excluded from going through the VPN tunnel.
> android: implement app split tunneling support

- Makefile
- README.md
#cleanup
Updated the notes on refreshing docker build containers 
Removed the jarsign output so we're not logging the jks password
> docs/makefile: update docker build instructions

- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
As discussed with @barnstar, let's hide health messages within the app's main screen unless they are high severity. Low and mid-severity messages will be re-added in a more subtle, later iteration with a dedicated health messages view.
> ui: only show high severity warnings in-app for 1.70

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SplitTunnelAppPickerView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SplitTunnelAppPickerViewModel.kt
- android/src/main/res/values/strings.xml
- android/src/main/res/xml/app_restrictions.xml
Updates tailscale/tailscale#6912
Adds two new Android-only MDM policies: IncludedPackageNames and ExcludedPackageNames. These are comma-separated string values that contain Android package names to configure app-based split tunneling programmatically.
If ExcludedPackageNames is non-empty, Tailscale will exclude the given apps from the VPN tunnel.
If IncludedPackageNames is non-empty, Tailscale will configure the VPN tunnel to only route the given apps via Tailscale.
> mdm: support split tunneling configuration via syspolicy

- Makefile
- android/build.gradle
updates tailscale/corp#21644
release_tv should init with the release target or it doesn't build the right thing.
> android/gradle: separate release and release_tv

- Makefile
- docker/DockerFile.amd64-build
updates tailscale/corp#21644
Docker ignores all but the last CMD invocation (silently).  These have to be combined into a single line. 
The clean is redundant.  We run a clean on the mounted directory before we kick off make docker-run-build.
The image name  is updated to ensure it's rebuilt.
> android/docker: combine CMD invocations into a single line

- android/build.gradle
- android/gradle.properties
- go.mod
- go.sum
Fixes #cleanup
Bumps OSS, updates dependencies and enables `android.nonTransitiveRClass` to improve build times.
> android: bump OSS to 1.71.x; update dependencies

- android/build.gradle
- go.mod
- go.sum
Last bump didn't update the version in the gradle file (unstable is still at 1.69).  This bumps again and sets the version to 1.71.
> android: bump oss and version code

- Makefile
bumposs was not properly setting the version.  Split the tasks into separate recipes.  Simply calling make bumposs should now generate a single commit with the proper versioning in build.gradle, the proper tags, and the proper changes to the go.mod and go.sum files.
> makefile: fix bumposs to properly set version and tag

- android/src/main/java/com/tailscale/ipn/App.kt
Since Google Stadia has been unavailable since 2023, there is no more need to list it as a default app exclusion.
> android: remove Google Stadia from hardcoded exclusions list

- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
We stringify setting values with `toString` before returning them from the `syspolicyHandler`. For enum setting types, such as `AlwaysNeverUserDecides` and `ShowHide`, the default `toString` implementation returns the enum constant names, such as `Always` and `UserDecides`. However, the Go backend requires us to return `always`, `never`, and `user-decides` values, exactly, and falls back to the default value (e.g., `user-decides`) if it receives anything else from the app.
This PR overrides the `toString` methods on both enums to return the required values rather than the constant names.
Updates tailscale/tailscale#12687
> mdm: return values rather than the constant names for the setting enums

- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- libtailscale/syspolicy_handler.go
Currently, `NoSuchKeyException` gets translated by gomobile to a Go error with "no such key" as the text. It is imperative for `syspolicy.Handler` implementations to return `syspolicy.ErrNoSuchKey` if a policy setting is not configured, so this PR adds translation for errors that do not already wrap `syspolicy.ErrNoSuchKey`, but have "no such key" as the text.
Updates tailscale/tailscale#12687
> libtailscale, android: translate NoSuchKeyException as syspolicy.ErrNoSuchKey

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
- android/src/main/java/com/tailscale/ipn/ui/util/PeerHelper.kt
- android/src/main/java/com/tailscale/ipn/ui/view/DNSSettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SplitTunnelAppPickerView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SplitTunnelAppPickerViewModel.kt
We should distinguish between unconfigured policy settings and those configured with the default values. In the first case, the `syspolicyHandler` should return `syspolicy.ErrNoSuchKey` instead of the default value, while in the latter case, it should return the actual setting value, even if that value happens to be the default value such as `user-decides`. This distinction should also be reflected in the "Current MDM settings" view.
In this PR, we update `MDMSetting.flow` to hold both the value to be used by the app and a flag indicating whether the policy setting is configured or not. If the policy setting is not configured, the value is the default value for the setting type. We then use this new flag to decide whether to throw a `NoSuchKeyException` from the Kotlin-side of the …
> mdm: improve handling and returning of not configured policy settings

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- libtailscale/backend.go
- libtailscale/interfaces.go
- libtailscale/localapi.go
- libtailscale/syspolicy_handler.go
- libtailscale/tailscale.go
In preparation for upcoming syspolicy improvements, we'd like to allow subscriptions to policy change notifications via the `syspolicyHandler.RegisterChangeCallback`. The registered callbacks are invoked whenever `MDMSettings.update` is called.
Updates tailscale/tailscale#12687
> libtailscale, mdm: allow syspolicy to subscribe to policy change notifications

- Makefile
updates tailscale/corp#21644
The docker build sill requires the recipe for bumping the version code by one before we run the second
androidTV build.  This was removed, which breaks the build.
> makefile: add bump_version_code recipe back

- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
- go.mod
- go.sum
Also pull in latest oss to avoid crashing if sharing fails.
Updates tailscale/corp#22357
> taildrop: use a random filename if real filename cannot be determined

- android/src/main/java/com/tailscale/ipn/VPNServiceBuilder.kt
Updates tailscale/tailscale#13106
Our code in VPNServiceBuilder attempts to call excludeRoute regardless of API level. However, it requires a device on Android API level 33 or newer. Let's document and log this while we plan a proper workaround.
> VPNServiceBuilder: document excludeRoute not supported on pre-33 API

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/VpnViewModel.kt
Currently, the VPN is prepared when MainActivity is launched. If Tailscale is enabled by a quick tile, the VPN is not prepared.
Fixes tailscale/tailscale#12489
> android: prepare VPN when quick tile is clicked

- android/src/main/java/com/tailscale/ipn/VPNServiceBuilder.kt
Reverts tailscale/tailscale-android#467
> Revert "VPNServiceBuilder: document excludeRoute not supported on pre-33 API"

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/ui/view/TaildropView.kt
- android/src/main/res/values/strings.xml
Updates tailscale/corp#22362
First round of polish for the Taildrop device picker, to use more consistent metrics and SectionDivider resembling the rest of the app. We'll follow up with device icons like the ones we have on iOS in a later PR.
> android: fix paddings and headers of Taildrop destination picker

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/res/values/strings.xml
Detect when another VPN is active and launch dialog giving user the option to navigate to settings to disable. Update state string and toggle to require successful VPN preparation
To do in a follow-up: monitor VPN connection, and if Tailscale VPN disconnects due to another VPN connecting, update toggle and text
Updates tailscale/tailscale#12850
> android: check if other VPN is active

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/res/values/strings.xml
- android/src/main/res/xml/app_restrictions.xml
- go.mod
- go.sum
Updates tailscale/tailscale#1572
This PR defines the AuthKey system policy in the Android codebase, allowing the code in OSS (see tailscale/tailscale#13061) to pick up any value defined by an MDM solution via managed app configuration. It also adds the new key to the `app_restrictions.xml`.
> mdm: add AuthKey piping

- android/src/main/java/com/tailscale/ipn/App.kt
Resolves: https://github.com/tailscale/tailscale/issues/12132
* Allows notification to be dismissed on Android 13 with the swipe gesture
* Sets `.setOngoing(false)` to be able to dismiss the notification, [docs](https://developer.android.com/reference/android/app/Notification.Builder#setOngoing(boolean))
| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/8295a035-3133-43b0-8f12-98c6d94b68e4" /> | <video src="https://github.com/user-attachments/assets/4aa26a54-cdd3-4cfa-bdda-9662beb4a597" /> |
> android: Allow notification dismissed via swipe on Android 13

- Makefile
updates #cleanup
The tag_release recipe was integrated with bumposs, but it's still needed to manually tag branches such as the release branch.
> makefile: add tag_release recipe

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/NetworkChangeCallback.kt
- android/src/main/java/com/tailscale/ipn/ui/model/Ipn.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/VpnViewModel.kt
- go.mod
- libtailscale/backend.go
- libtailscale/interfaces.go
- libtailscale/net.go
-add new Ipn UI state 'Stopping' to handle the case where the VPN is no longer active and a request to stop Tailscale has been issued (but is not complete yet) and use for optimistic UI 
-when VPN has been revoked, stop tailscaled and set the state to Stopping 
-this fixes the race condition where when we tell tailscaled to stop, stopping races against the netmap state updating as a result of the VPN being revoked 
-add isActive state and use instead of isPrepared for UI showing whether we are connected - we were previously using isPrepared as a proxy for connection, but sometimes the VPN has been prepared but is not active (eg when VPN permissions have been given and VPN has been connected previously, but has been revoked) 
-refactor network callbacks into its own class for readability …
> android: stop tailscaled when VPN has been revoked

- android/src/main/java/com/tailscale/ipn/ui/util/ClipboardValueView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt
also, use Column isntead of LazyColumn since the Tailnet lock view is a short list and doesn't require lazy rendering
Fixes tailscale/corp#21737
> android: make clipboard values clickable and focusable

- Makefile
- android/build.gradle
- go.mod
- go.sum
- version/tailscale-version.sh
updates #cleanup
Fixes the versioning script to always use the toolchain from the tailscale.com repo.
Updates the docker container names so we regenerate them due to the toolchain changes.
Bumps OSS to 1.73.104
Signed-off-by: Jonathan Nobels <jonathan@tailscale.com>
> android: fix versioning and bump oss

- android/src/main/java/com/tailscale/ipn/App.kt
- libtailscale/backend.go
- libtailscale/interfaces.go
- libtailscale/net.go
- libtailscale/tailscale.go
Rather than create a Go struct that is set by Android, have Go call into Android to fetch build BuildConfig Updates tailscale/tailscale#13431
> android: fix BuildConfig infinite loop

- Makefile
- docker/DockerFile.amd64-build
updates tailscale/corp/issues#17686
'make clean' will now purge the cached toolchain to ensure you're using the right go version when switching branches.  make clean is run by the docker image before building anything and the docker image name is updated to force a rebuild of the image.
Also included a note of the image naming convention for docker build images to include a date, for traceability.
> android: fix clean build

- Makefile
Go has a new build facility that can utilize other toolchains if a module says so, but we manage the toolchain in our own way, so disable it.
Updates #501
> Makefile: disable GOTOOLCHAIN from dynamic switching

- Makefile
The go wrapper script in tool/go assumes that .extracted is representative of the state of the toolchain directory, so it must be removed when the toolchain directory is removed.
Updates #501
> Makefile: remove go toolchain version marker in clean as well

- tool/go
The wrapper script was not checking for changes in the extracted version vs. the revision file.
Updates #501
> tool/go: update the toolchain if it is old

- Makefile
Make does not respect PATH updates made inside the Makefile for program lookup in invocations. This can be worked around a number of ways, but the most broadly robust is to explicitly update PATH by overriding SHELL.
Updates #501
> Makefile: fix PATH resolution on macOS builds of gmake

- android/src/main/java/com/tailscale/ipn/ui/view/CustomLogin.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/CustomLoginViewModel.kt
> android: make custom url check case-insensitive

- android/src/main/java/com/tailscale/ipn/App.kt
Previously we were never actually invoking this parameter 
We previously weren't setting vpnActive after closing IPNService
Updates tailscale/corp#22284
> android: use onSuccess parameter in setWantRunning

- Makefile
- build-tags.sh
Updates tailscale/tailscale#13527
> Makefile: use "tailscale_go" build tag when using Tailscale's Go toolchain

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/NetworkChangeCallback.kt
- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
- android/src/main/java/com/tailscale/ipn/StartVPNWorker.java
- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/HealthNotifier.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/Notifier.kt
- android/src/main/java/com/tailscale/ipn/ui/util/TimeUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/DNSSettingsViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/IpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/PingViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/TaildropViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/VpnViewModel.kt
- android/src/main/java/com/tailscale/ipn/util/TSLog.kt
- android/src/test/kotlin/com/tailcale/ipn/ui/util/TimeUtilTest.kt
- libtailscale/callbacks.go
- libtailscale/interfaces.go
- libtailscale/tailscale.go
ExtendedLog sends log messages to Android's logcat and Tailscale's logger Libtailscale wrapper is a Kotlin wrapper that allows us to get around the problems with mocking a native library
Fixes tailscale/corp#23191
> android: send Android logs to logz

- android/build.gradle
- android/src/main/java/com/tailscale/ipn/AppSourceChecker.kt
- android/src/main/java/com/tailscale/ipn/QuickToggleService.java
- android/src/main/java/com/tailscale/ipn/ui/model/Permissions.kt
- android/src/main/java/com/tailscale/ipn/ui/theme/Theme.kt
- android/src/main/java/com/tailscale/ipn/ui/util/AndroidTVUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MDMSettingsDebugView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/ManagedByView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
#Updates tailscale/corp#22284
Fixes and/or explicitly suppresses all linter warnings and we will now fail the build if new warnings are introduced.
> android: fix all linter warnings and treat warnings as errors

- android/src/main/java/com/tailscale/ipn/IPNService.kt
This is mainly a no-op; right now we are setting the VPN status when we successfully edit prefs with wantRunning=false, but the VPN status is separate from tailscaled status and reflects the status of the VPN interface. This change moves that status update into the Android Service APIs.
Updates tailscale/tailscale#12850
Updates tailscale/tailscale#12489
> android: set VPN status in service APIs

- android/src/main/java/com/tailscale/ipn/IPNService.kt
- libtailscale/backend.go
- libtailscale/interfaces.go
- libtailscale/net.go
We are currently setting vpnService.service to nil: -any time there’s an error with updateTUN
-when we exit out of runBackend
-if the config is the default config (aka when the ipn state is Stopped)
When it gets set to nil, we don’t handle state or config updates by calling updateTUN until after startVPN is called again. The second case never happens because there’s no condition to break out of the loop in runBackend and ctx is uncancelable per the doc for context.Background() In the third case, we should not establish the VPN; the state is already in the correct Stopped state, but there’s no need to set the service to nil and prevent updateTUN from being called. The quick settings tile bug is caused by this third case, where because the saved prefs starts the app up in the Stopped state, …
> android: don't set vpnService to nil when state is Stopped

- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsDefinitions.kt
getFromBundle should check for both String[] and ArrayList<String>
Fixes tailscale/corp#23557
> android: StringArrayListMDMSetting should check for String[]

- android/src/main/java/com/tailscale/ipn/ui/model/IpnState.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt
Fixes tailscale/corp#23660
Brings each row of the account switcher to parity with iOS by using `LoginName` instead of `DisplayName`, and showing a custom control server hostname as a third row when it is set.
> ui/UserView: show custom control server URL in account switcher

- android/src/main/java/com/tailscale/ipn/ui/model/IpnState.kt
Updates tailscale/corp#23660
I screwed up by not including 'https://' in a last-minute refactoring :-)
> ui/model: adjust default control server URL

- android/build.gradle
- go.mod
- go.sum
OSS and Version updated to 1.75.81-t4ad3f0122-g0126db799b1
> android: bumping OSS

- android/src/main/java/com/tailscale/ipn/App.kt
Use FLAG_UPDATE_CURRENT for managing multiple calls to startForegroundService. This ensures only one instance of the intent is active and replaces any previously pending intents with the latest one.
Fixes tailscale/corp#23828
> android: handle multiple redundant intents

- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
-Apply focusable() directly to outer Box instead of nested with clickable() 
-Explicitly handle focus
-Simplify focusable area
Fixes tailscale/corp/#23762
> android: fix avatar focusable

- android/src/main/java/com/tailscale/ipn/ui/util/ClipboardValueView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TailnetLockSetupView.kt
-use a shared InteractionSource for focusing and clicking to ensure they rely on the same state and to coordinate so that visual feedback is shown on scroll without affecting the click InteractionSource 
-use LocalIndication to ensure that the click interaction maintains the visual feedback when combined with focusable 
-use onFocusChanged to explicitly track the focus state
Updates tailscale/corp#21737
> android: make tailnet lock setup view focusable and clickable

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
In notification, don't show 'Disconnect' button if MDM force enable is on.
Fixes tailscale/corp#23764
> android: hide disconnect action if force enabled

- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
Android TV has limited support for notifications compared to mobile - notifications are not show in the system UI to provide a leanback experience. Remove 'Permissions' from Settings menu.
Fixes tailscale/corp/#21034
> android: don't show permissions for TV

- .github/workflows/android.yml
- Makefile
The explicit target was removed during patch production, but the dependency wasn't removed from the clean action.
Updates #546
Updates tailscale/tailscale#13850
> Makefile: fix clean action dependencies

- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
contentResolver.query is attempting to perform a network query on the main thread. Move this to a coroutine to prevent blocking.
Fixes tailscale/corp#24293
> android: use a coroutine for loadfiles

- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
Update Avatar to take isFocusable as a parameter, allowing us to make the avatar focusable in the main view but not in the settings / user switcher view. This fixes the issue where the padding is too big in the settings / user switcher view.
Fixes tailscale/corp#24370
> android: fix avatar padding

- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
Always render the default icon first so that if the profile picture is not loaded or has an issue, the default is shown.
Fixes tailscale/corp#24217
> android: fix issue where default avatar wasn't shown

- go.mod
- go.sum
OSS and Version updated to 1.77.113-t00517c818-ge95b7b7f6
Rebumping after fixing OSS -pre tags.
> android: bump OSS

- Makefile
updates tailscle/corp#24686
We must ensure the correct version file exists before kicking off any of the apk or aab builds.  This also revs the docker image so we're picking up the latest toolchain.
> Makefile: run version before attempting to build the apk/aab

- android/src/main/java/com/tailscale/ipn/App.kt
Default to excluding Adaptive Connectivity Services to fix issue where it is erroneously classifying wifi as broken
Fixes tailscale/tailscale#14128
> android: exclude Adaptive Connectivity Services

- android/src/main/java/com/tailscale/ipn/App.kt
Also log if get() is still being accessed before onCreate initializes appInstance so we can understand if this is still happening. Also remove a debug log that I forgot to delete.
Updates tailscale/tailscale#14125
> android: initialize appInstance early

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
-Lazily init app in Client to ensure that we aren't trying to make any local API calls before app has been initialized. 
-Add @Volatile to ensure that isInitialized is always visible across threads and uses the updated value
Updates tailscale/tailscale#14125
> android: lazily init app in Client

- android/src/main/java/com/tailscale/ipn/ShareActivity.kt
If contentResolver.query returns null, or the URI is invalid, skip processing and log instead of crashing. Also, use 'use' for the cursor instead of 'let' to automatically close the cursor after processing.
Fixes tailscale/corp#24293
> android: handle null query results in ShareActivity

- android/proguard-rules.pro
Updates tailscale/tailscale#14162
> android: modify proguard rules to not mangle Tailscale app symbols

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsChangedReceiver.kt
In this PR, we update the Android app to register a broadcast receiver that listens for `android.content.Intent.ACTION_APPLICATION_RESTRICTIONS_CHANGED` and updates `MDMSettings` whenever a change occurs. This, in turn, notifies the Go backend and causes it to reload syspolicy, ensuring it reflects the updated MDM settings.
Updates tailscale/tailscale#12687
> mdm: update MDMSettings (and syspolicy) when application restrictions change

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/ui/notifier/HealthNotifier.kt
Updates tailscale/tailscale#12960
When the client is Stopped after running, a false positive DERP warning was getting presented. This was not happening on Apple platforms because we never leave the client in a Stopped state, the extension instantly terminates. Since that's not the case on Android, this PR ensures that:
- we do not present any warnings when the client is Stopped (nothing should be broken when nothing is running)
- if we enter the Stopped state, any pre-existing warnings generated while the client was running are dropped
> HealthNotifier: prevent and drop all warnings in the Stopped state

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/ui/util/ModifierUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
fixes tailscale/corp#24847
fixes tailsacle/corp#24848
Search jobs are moved to the default dispatcher so they do not block the UI thread.
The avatar boxing is now used only conditionally on AndroidTV.
> android: move node search to background and fix avatar padding

- android/src/main/res/values/strings.xml
Updates the login UI to provide the input code location in the admin console.
Fixes tailscale/corp#24837
> android: update hex input code instructions for TV log in

- android/src/main/java/com/tailscale/ipn/ui/view/LoginQRView.kt
- android/src/main/res/values/strings.xml
Add a rounded box around the hex code and emphasize the code with font/styling
Updates tailscale/corp#24837
> android: emphasize hex code in TV login

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/mdm/MDMSettingsChangedReceiver.kt
Per https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported, we need to register all receivers.
Fixes tailscale/corp#25021
> android: specify whether or not receivers are exported

- android/src/main/java/com/tailscale/ipn/VPNServiceBuilder.kt
updates tailscale/corp#25083
excludedRoutes is only supported on API 33 and up so it needs a version check.
> android: omit excludedRoutes for API<33

- android/src/main/java/com/tailscale/ipn/ui/view/ExitNodePicker.kt
excludeRoute is only supported on API 33+, so we are not supporting allow LAN access for older versions. To avoid confusion, don't show the option if the feature is not enabled.
Updates tailscale/corp#25083
> android: hide allow LAN access if feature not enabled

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PeerDetails.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SearchView.kt
- android/src/main/res/values/strings.xml
-Material3 search bar opens up search suggestions/results view under the bar, but we want it to open up a full page, so create SearchView and use placeholder search bar on MainView that navigates to SearchView -Tapping on suggestions/results should open up PeerDetails, so fix PeerDetails navigation to use backstack instead of always going back to Main view
Next up: ensuring search filtering adheres to MDM requirements, and UI polish
Updates tailscale/corp#18973
> android: add SearchView

- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
Pass in intended state to toggleVpn and keep track of progress to avoid redundant updates and ensure that the action taken reflects the user's intent. This fixes a possible recomposition loop caused by the ipn state and the vpn toggle state getting out of sync.
Updates tailscale/tailscale#14125
> android: synchronize ipn state and UI

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
- android/src/main/java/com/tailscale/ipn/util/TSLog.kt
Updates tailscale/tailscale#14125
> android: add logging to see what's spamming editPrefs

- .github/workflows/android.yml
- .github/workflows/go_mod_tidy.yml
Previously, using `*` in branch filters prevented PR CI actions from running on prefixed branches such as `release-branch/*` because `*` only matches characters except for forward slashes. In this PR, we remove the branch filter to ensure that Android builds and go mod tidy checks are executed on all PRs, regardless of the target branch. Additionally, these checks will now run on pushes to `release-branch/*`.
Fixes tailscale/corp#25313
> github/workflows/{android,go_mod_tidy}: run on all PRs and on pushes to {main,release-branch/*}

- android/src/main/AndroidManifest.xml
Mark the Quick Settings tile as toggleable.
The primary function of the Quick Settings tile is to turn on or of the VPN connection so it should be marked as toggleable as per the Android guidelines: https://developer.android.com/develop/ui/views/quicksettings-tiles#mark-tile
This also removes the little chevron on the tile which should only be shown on tiles that open a dialog or activity.
> android: mark Quick Settings tile as toggleable

- android/src/main/java/com/tailscale/ipn/mdm/MDMSettings.kt
- android/src/main/res/values/strings.xml
- android/src/main/res/xml/app_restrictions.xml
Updates tailscale/corp#25936
Adds a definition for the Hostname syspolicy which we are adding in OSS: https://github.com/tailscale/tailscale/pull/14676
Also adds it to the app_restrictions.xml file so that MDM solutions can pick it up.
> mdm: define Hostname syspolicy on Android

- android/src/main/res/values/strings.xml
Updates a typo in the subnet router "add route" menu from "a IPv4" to "an IPv4"
Fixes tailscale/corp#26167
> android: fix typo in subnet menu

- android/src/main/java/com/tailscale/ipn/ui/view/ErrorDialog.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SubnetRoutingView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SubnetRoutingViewModel.kt
- android/src/main/res/values/strings.xml
Fixes tailscale/corp#26175
When setting subnet routing settings, for a variety of reasons the Tailscale backend may reject an entered value with a 400 error. Here we handle such errors in a user-facing fashion:
- We display an ErrorDialog with title 'Failed to save' and whatever error message the backend request returned. To do so, we introduce a new initializer for ErrorDialog that accepts a runtime-generated String instead of a fixed string resource.
- We ask the backend to provide an updated value of AdvertiseRoutes whenever the error dialog is dismissed by the user, and set it as the UI state, to ensure consistency between UI and backend upon a failed save.
> ui: display error dialog when saving subnet routes fails

- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SharedViews.kt
updates tailscale/corp#26199
The back buttons would not highlight properly when they are focussed on Android TV.  This pulls in what was implemented for the Avatar.
Some small tweaks to the action animation so that it has a nice radius instead of a square box.
> android/tv: fix focus highlighting on back buttons

- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserView.kt
updates tailscale/corp#26199
Removes the avatar padding when the avatar is not focusable on AndroidTV.
> android/tv: remove avatar padding in userView

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
A possible cause for an IndexOutOfBounds exception is that when the intent is delivered, the back stack doesn't have enough entries for the operation. Condition popping back on if there is more than one entry in the back stack; otherwise, navigate directly to main to reset the back stack.
Updates tailscale/tailscale#15188
> android: check back stack before popping back

- .gitignore
- Makefile
- Added Makefile targets to build an unstripped version of the libtailscale AAR.
- Extracted the native .so (libgojni.so) from the unstripped AAR.
- Generated a debug symbols file (libgojni.so.debug) using llvm-objcopy with --only-keep-debug.
- Stripped the native library (libgojni.so.stripped) with --strip-debug and repackaged the final AAR.
This allows the build chain to produce a stripped AAR for the app and a separate debug symbols file that can be uploaded to Google Play for crash deobfuscation.
Signed-off-by: kari-ts <kari@tailscale.com>
Updates tailscale/tailscale#15210
> Makefile: make unstripped libtailscale and debug symbols

- Makefile
- docker/DockerFile.amd64-build
- docker/DockerFile.amd64-shell
Updating our base builder to eclipse-temurin:21 for compatibility with dependencies.  Updating the default
toolchains to speed up the build.
Updates tailscale/tailscale#15210
> android: update base builder image

- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
disable search for Android TV running < API 33
Updates tailscale/corp#27375
> android: only use new search for API 33+

- .github/workflows/android.yml
- .github/workflows/go_mod_tidy.yml
- .github/workflows/license-headers.yml
Pin versions of GitHub actions that are used in our workflows.
Bumps an instance of actions/checkout from v3.x to v4.x.
Bumps actions/setup-java from v3.x to v4.x.
> .github/workflows: pin GitHub action versions

- android/build.gradle
Update to androidx.navigation 2.8.5: this fixes the NavHost exception per https://developer.android.com/jetpack/androidx/releases/navigation#2.8.5
Fixes tailscale/tailscale#15755
> android: fix IllegalStateException in navigation

- android/src/main/java/com/tailscale/ipn/ui/localapi/Client.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
Right now, we register the launcher in MainActivity.onCreate(), inject this into the ViewModel, then show the launcher in MainView. There is no guarantee that the activity is in RESUMED when the Composable runs, showing the launcher. This can lead to a silent RESULT_CANCELED on some OEMs. The fix is to add a lifecycle-aware wrapper that defers the launch.
Updates tailscale/tailscale#15419
> android: defer vpn permission until activity is resumed

- android/src/main/java/com/tailscale/ipn/ui/model/TailCfg.kt
&& takes precedence over ?:, so fix isExitNode to check both IPv4 and IPv6
Updates tailscale/tailscale#15785
> android: fix isExitNode check

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/IPNService.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/SplitTunnelAppPickerViewModel.kt
We were previously calling startService(intent), which is a direct call consumed by IPNService, but restartVPN was not working as intended because the broadcast receiver was never triggered. Rather than use a broadcast receiver, directly start the service in restartVPN as we do in stopVPN. Also, batch changes to excluded apps so that we don't restart the VPN each time the user toggles an app.
Fixes tailscale/corp#28668
> android: replace broadcast intent with service intent

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/util/OutputStreamAdapter.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/util/ShareFileHelper.kt
- libtailscale/backend.go
- libtailscale/callbacks.go
- libtailscale/fileops.go
- libtailscale/interfaces.go
- libtailscale/tailscale.go
Use Android Storage Access Framework for receiving Taildropped files.
-Add a picker to allow users to select where Taildropped files go
-If no directory is selected, internal app storage is used
-Provide SAF API for Go to use when writing and renaming files
-Provide Android FileOps implementation
Updates https://github.com/tailscale/tailscale/issues/15263
> android: use SAF for storing Taildropped files

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/TaildropDirectoryStore.kt
- android/src/main/java/com/tailscale/ipn/ui/util/PermissionsDisplayUtil.kt
- android/src/main/java/com/tailscale/ipn/ui/view/NotificationsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PermissionsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TaildropDirView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/PermissionsViewModel.kt
- android/src/main/res/drawable/baseline_drive_folder_upload_24.xml
- android/src/main/res/drawable/baseline_folder_open_24.xml
- android/src/main/res/drawable/baseline_notifications_none_24.xml
- android/src/main/res/values/strings.xml
-Modify Permissions view to navigate to Taildrop dir view and Notifications view, and to reflect state -Add Taildrop dir view which navigates to directory selector -Add Notifications view which navigates to Taildrop notifications setting
Updates tailscale/tailscale#15263
> android: allow users to update taildrop directory

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/TaildropDirectoryStore.kt
- android/src/main/java/com/tailscale/ipn/ui/view/PermissionsView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/TaildropDirView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/PermissionsViewModel.kt
-The composables were reading the currentDir value once and not observing it. This fixes it so that we recompose when the StateFlow changes. -Use commit() instead of apply() when writing to EncryptedSharedPreferences since we are reading from it immediately and need the writes to happen synchronously
Fixes tailscale/corp#29283
> android: make currentDir reactive

- android/src/main/java/com/tailscale/ipn/ui/util/AndroidTVUtil.kt
fixes tailscale/tailscale#16164
We weren't detecting fire stick devices as TV devices.
> android: detect amazon fire stick as a AndroidTV

- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/res/values/strings.xml
Some heavily customized OEMS may auto-deny VPN requests without exposing the setting. Show a fallback dialog for devices with no visible VPN panel.
Updates tailscale/tailscale#14095
> android: add fallback VPN permission

- android/src/main/java/com/tailscale/ipn/ui/model/NetMap.kt
- android/src/main/java/com/tailscale/ipn/ui/view/UserSwitcherView.kt
- android/src/main/res/values/strings.xml
Add dialog for deleting tailnet in user switcher view.
Future improvement will be to use a pre-filled support form. Web team is currently overhauling the support form, but plan to add support so we can link to a pre-filled form.
Fixes tailscale/corp#31024
> android: add tailnet deletion dialog

- android/src/main/java/com/tailscale/ipn/App.kt
- android/src/main/java/com/tailscale/ipn/MainActivity.kt
- android/src/main/java/com/tailscale/ipn/TaildropDirectoryStore.kt
- android/src/main/java/com/tailscale/ipn/ui/view/MainView.kt
- android/src/main/java/com/tailscale/ipn/ui/view/SettingsView.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/AppViewModel.kt
- android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt
- android/src/main/java/com/tailscale/ipn/util/ShareFileHelper.kt
- libtailscale/backend.go
- libtailscale/callbacks.go
- libtailscale/interfaces.go
- libtailscale/tailscale.go
Move Taildrop directory selector out of onboarding -Listen for Taildrop, and show selector if a directory has not been set
Remove LocalBackend re-initialization
-This is no longer necessary since the directory is set in FileOps
Updates tailscale/corp#29211
(cherry picked from commit e68e64014ea0f9ee4ccc11d042119e0413accf5b)
> android: defer taildrop selector until first taildrop attempt (#684)

- libtailscale/backend.go
- libtailscale/syspolicy_handler.go
- libtailscale/tailscale.go
Updates tailscale/tailscale#17022
> libtailscale: use syspolicy RegisterStore rather than deprecated RegisterHandler

- android/src/main/java/com/tailscale/ipn/ui/view/Avatar.kt
fixes tailscale/corp#32012
We need to hide the placeholder once the user's avatar is loaded or transparent avatars show the placeholder.
> android: hide placeholder when avatar is loaded
